### ISSUE TITLE
[DCC] How to handle complex units

### ISSUE THREAD

**Issue by heikowestermann** [IEA-Task-43/digital_wra_data_standard#100]
Currently the unit of a `quantity` is a required field. unit is an enum inherited from the WRA schema. While the enum captures most cases, I have run into the problem that the unit of the slope of a calibration result can be in the form "m*s^-1 / Hz". There are a few ways to handle this:

    1. make the unit field optional
    2. add necessary units to the enum (formally correct in my opinion, but messy as there are many possible unit combinations)
    3. add 'null' / not available unit (or equivalent) to the enum
    4. remove enum requirement

I prefer 3. as this won't affect the requirement of the field and therefore water down the necessity to add a unit, and also is easier to implement than to add all possible combinations of a unit. The downside is that the information about the unit is missing.

**Comment by kersting** [comment]
@heikowestermann I would go with 2 knowing that is more complicated because I'm aware of old calibration certificates (non measnet) that the calibrations are provided in miles per hour and I think also in knots. Also, we don't need to add all possible units but only those that are relevant to the calibration certificate parameters.

**Comment by stephenholleran** [comment]
@heikowestermann @kersting 

I would be inclined to go with 2 as well and try and capture as many as we can.
We could also do 3 as well so a user isn't blocked if we haven't captured the particular one they are looking for?

**Comment by heikowestermann** [comment]
I was ready to add the missing units, but noticed that we might some room for discussions. Below is my proposed list of units for the enum. I removed the following units, as they are not applicable for an anemometer calibration: ```W/m^2, m/s^2, lux, dB```

Current
-------

- "m/s"
- "deg"
- "deg_C"
- "deg_F"
- "K"
- "%"
- "mbar"
- "hPa"
- "V"
- "mA"
- "ohm"
- "Hz"
- "mm"
- "W/m^2"
- "m/s^2"
- "lux"
- "dB"
- "-"

Propossed
---------
- "m/s"
- "deg"
- "deg_C"
- "deg_F"
- "K"
- "%"
- "mbar"
- "hPa"
- "V"
- "mA"
- "ohm"
- "Hz"
- "mm"
- "-"
- **"cm/s"**
- **"km/h"**
- **"mph"**
- **"knots"**
- **"V/(m/s)"**
- **"mA/(m/s)"**
- **"Hz/(m/s)"**
- **"-/(m/s)"**
- **"(cm/s)/(m/s)"**
- **"(km/h)/(m/s)"**
- **"mph/(m/s)"**
- **"knots/(m/s)"**


@kersting I remember that you mentioned some old certificates where the reference unit was not m/s but mph. Is that correct? If so, I will add the combined units for that (e.G. Hz/mph)

Also, is everybody on board with the format using brackets "(unit) / (unit)"? I think from a parsing standpoint this should be fine, but I am open for alternative suggestions.

**Comment by heikowestermann** [comment]
The above units were inverted, see #137

**Comment by heikowestermann** [comment]
the unit **(m/s)/(m/s)** is missing. It can be argued that the unit would then be **-**, but I think it's wise to add it to the list.

**Comment by stephenholleran** [comment]
@heikowestermann go for it. What would be the use case for it or is it just to be complete?

**Comment by heikowestermann** [comment]
It's just to be complete, as I ran into the issue.

**Comment by stephenholleran** [comment]
Sounds good @heikowestermann. Go for it.

A consequence of this is that we will now have to add a version number to the DCC :) #147

**Comment by stephenholleran** [comment]
Implemented in #183
