### ISSUE TITLE
Additional non analysis Field in Level1.3 Logger Main Config

### ISSUE THREAD

**Issue by agrangaraj** [IEA-Task-43/digital_wra_data_standard#105]
The following fields may not directly impact calculation but can we consider to include the following fields as an optional additional static details fields so that WRA data model can be used for both data analysis and to know the various static information about WRA project. 

1. Logger OEM id: Nomad, Kintech, Ammonit, NRG etc.,
2. Datalogger configuration home page url
3. User name
4. Password
5. Sim card Service provider name 
6. Sim card IMEI number 
7. Mobile Number
8. MAC address of network device
9. Logger configured by 
10. Designation
11. Phone number
12. OEM Service center name
13. OEM serivce center Address
14. OEM service center Contact number
15. Modem details
16. Static IP address

**Comment by abohara** [comment]
Hi @agrangaraj 

Please see [sql file](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/tools/iea43_wra_data_model_postgresql.sql) for the logger OEM id.

A lot of the details here seem useful for the data manager monitoring a measurement station but not necessarily for a resource assessment. However, these are fields that could be added to a local deployment in the [`logger_config`](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/docs/iea43_wra_data_model-properties-measurement-location-measurement-location-properties-logger-configuration-logger-configuration.md) table. 

@stephenholleran , @kersting  could chime in.

**Comment by stephenholleran** [comment]
Hi @agrangaraj,

I agree with @abohara that these are all very useful for the management of the mast but are not useful when assessing the data.

"_Logger OEM id: Nomad, Kintech, Ammonit, NRG etc.,_" is captured already.

Username, password, SIM card IMEI number, Mobile Number, Static IP address are all fields that you wouldn't want to be sending around from one organisation to another. We previously decided that personal info and info that can allow others to connect to the logger shouldn't be included. In saying that we do include `encryption_pin_or_key` however this is required for a wind analyst to actual process the raw files so is required.

At the very least we should make `additionalProperties` and `additionalItems` to  true so these items can be added by a user if they wish.

**Comment by stephenholleran** [comment]
In the new version (if approved), additional properties can now be added to a `logger_main_config`.

Example below where the properties 'username' and 'password' is added:

```json
"logger_main_config": [{
      "logger_serial_number": "01002",
      "logger_model_name": "Symphonie Plus3",
      "logger_id": "4321",
      "logger_oem_id": "NRG Systems",
      "logger_name": "AName_MM1",
      **"username": "something"**
      **"password": "something"**
      "date_from": "2020-04-12T12:00:00",
      "date_to": "2021-04-12T12:00:00"
    }],
```
