### ISSUE TITLE
Additional Fields in Measurement Point Level.

### ISSUE THREAD

**Issue by agrangaraj** [IEA-Task-43/digital_wra_data_standard#106]
We can include following attributes in Level 1.4 of WRA data model

1. Measurement type: Rain (true or False), u, v, w, Sound (db), if we desired to expand this WRA model to wind power level we can consider to include Cumulative Energy, Daily Energy, Phase angle, Battery Power, 
2. Sensor_config->Measurement Unit id: km/hr, knot/s, mV, Whr, degree

The following field may not directly impact calculation but can we consider to include the following fields as an optional additional static details fields so that WRA data model can be used for both data analysis and to know the various static information about WRA project.

3. Sensor->Calibration: 1. Next calibration due, 2. Calibration center address, Phone number, Contact person name, Designation

**Comment by kersting** [comment]
@agrangaraj thanks for sending these over. Here are my comments.

Measurement type

- Rain: I'm not very familiar with noise assessment but I believe rain gauges are used for noise assessment. Is that correct?
- u, v, and w: These may be helpful if one is working with vector averaging.
- Regarding the additional parameters that you mentioned I'm not familiar with them.

Sensor config

@stephenholleran we had a discussion about derived units when we were working with digital calibration certificates but I cannot remember what was the decision. Do you recall what was the decision?

Sensor:

I see many comments regarding calibrations. We have worked in a standard for digital calibration certificates. Some of the fields that you are considering actually have influence in energy assessments. For the data model we're trying to keep the model lean with only information that has direct impact in the energy calculations.

**Comment by stephenholleran** [comment]
As discussed in the meeting on 14th oct 2021 https://github.com/IEA-Task-43/digital_wra_data_standard/issues/77#issuecomment-943505382 we decided to incorporate u, v and w vector components.

`Precipitation` is already available to cover `rain`. If a true/false is required, this measurement type can still be used as the values and units are independent from the measurement type. Or the 'status' type could be used.

`Power` and `energy` are already covered.

**Comment by stephenholleran** [comment]
Regarding measurement units, a lot of the ones suggested will be covered by @heikowestermann based on his https://github.com/IEA-Task-43/digital_wra_data_standard/issues/100#issuecomment-948440244
Others already exist such as 'kWh' to cover 'Whr', 'deg' to cover 'degrees'.
I am not sure of the usefulness of 'mV'. @agrangaraj if you could explain that would be great.

**Comment by kersting** [comment]
@agrangaraj could you please given an example on how is cumulative energy used in resource assessment?

**Comment by stephenholleran** [comment]
> @agrangaraj could you please given an example on how is cumulative energy used in resource assessment?

I'm sure it isn't used in a resource assessment but it might be useful depending on what is been tracked by a small turbine or solar panels charging the battery. If these are charging a lidar they could be big enough and they may have cumulative energy. I don't see the harm in adding it but I do realise that I may open the flood gates.

**Comment by kersting** [comment]
My view is that as long as it has an application in resource assessment, it should be added otherwise not because it opens the door to add anything else and we will end up with an oversized model that is not appealing for new adopters. If a logger's battery is charged with a turbine that logs cumulative energy then I see it as useful.

I asked for an example to try to understand why this would be useful for resource assessment. I hope that the example can clarify why such variable is important.

**Comment by abohara** [comment]
If we are going to have cumulative energy, we would need to be more descriptive e.g. cumulative from start of life or specific date, or cumulative daily or monthly. That said, I agree with @kersting  I can't recall a usecase where this has a direct bearing on WRA (though common in SCADA systems). It is far enough removed that perhaps the user can modify a local deployment to add this as a custom field.

**Comment by stephenholleran** [comment]
Fair points. I have removed it.
