### ISSUE TITLE
Explicit coordinate system, usage of EPSG code

### ISSUE THREAD

**Issue by NikoSimisiroglou** [IEA-Task-43/digital_wra_data_standard#119]
Hi, 

This is my first post, so firstly I would like to thank you for all this wonderful work you have done putting together this database, it is really impressive and well thought through. Now to the topic at hand and the reason for this post, I will advocate for the usage of an explicit unique identifier for the coordinate system and to log that in the database as opposed to the current description **or only** the description. The unique identifier I propose is the EPSG code, the EPSG code is a unique identifier for all the geodetic parameters in the dataset and thus removes any kind of ambiguity of what coordinate system you are using. For example the epsg code 4326, I believe is the coordinate system implied by this description: 

"Longitude coordinate in the Geographic Coordinate System using the WGS84 datum in decimal degrees. Longitude lines are perpendicular to the equator where their position ranges from 0° at Greenwich Mean Time increasing to +180° as you move eastward and decreasing to −180° as you move westward.",

 More info can be found here https://epsg.io/4326, about the 4326 EPSG code. Looking forward to your replies and insight.

**Comment by stephenholleran** [comment]
Hi @NikoSimisiroglou,

Thanks for post. 
We had a chat in our biweekly call today and agree that this is something we can be more explicit about.

At the start of developing this we decided that trying to account for all the coordinate systems out there was too much for us so we decided to limit it to Lat, Long values that GPS uses. By limiting it we don't really need an attribute to contain it as it is always the same. So the description is where we state what it should be. I realize that Europe has a slightly different datum compared to the US (I am not a GIS person) so been more explicit is good. As a first iteration of this simply updating the description is an easy win. Would the following work do you think, changes are in code blocks?

_"Longitude coordinate in the Geographic Coordinate System using the WGS84 `reference coordinate system, [EPSG:4326](https://epsg.io/4326). Unit of measure is` decimal degrees. Longitude lines are perpendicular to the equator where their position ranges from 0° at Greenwich Mean Time increasing to +180° as you move eastward and decreasing to −180° as you move westward."_

Is "Geographic Coordinate System" the correct term also?
Thanks!

**Comment by NikoSimisiroglou** [comment]
Hi @stephenholleran 

Thank you for your reply and consideration of my post.

Starting from your question: Usually when referring WGS84 people tend to mean the Geographic Coordinate System (GCS) and not the datum, spheroid or something else. This coordinate system has a unique identifier or WKID. The Well-Known ID (WKID) is a unique number assigned to a coordinate system, if the authority is EPSG that unique identifier is 4326 for the GCS of WGS84. This EPSG code will ensures that the projection system and datum is properly referenced. I know of one more authority for unique identifiers and that is ESRI. The numbers of these two authorities (EPSG and ESRI) do not overlap.

Expanding on my previous post and trying to be more inclusive and generic as to take into account other authorities of GCS, I would suggest to have a separate field where the WKID is explicitly defined and not buried in the description. Nevertheless, as a last resort using it in the description gives more clarity in my view than the alternative of not having it at all. 

By looking at the json file of the database schema, I think a suitable position for the WKID field would be under measurement_location. Perhaps the field could look like this:

"WKID": {
            "type": "number",
            "Authority": "EPSG" or "ESRI",
            "description": "The Well-Known ID (WKID) is a unique number assigned to a coordinate system.",
            "examples": [
             4326
            ], 

Please let me know what you think, thanks!

**Comment by stephenholleran** [comment]
Hi @NikoSimisiroglou,

We had a discussion about the use of a new WKID https://github.com/IEA-Task-43/digital_wra_data_standard/issues/77#issuecomment-990046659

> We should define what the coordinate system should be to avoid confusion. Having an attribute called WKID suggests to the user that they can set the coordinate system they are using. This can cause major confusion and updates to the Data Model as we would then have to account for Easting and Northing. It was decided to just update the description to be more specific about the coordinate system everyone should use.

Basically having a WKID property means that the user can set their own coordinate system which is what we want to avoid, for now. I'll update the description and send you a pull request. I hope this is somewhat satisfactory for you? 

Thanks again for bringing this up! It is good to be specific.

**Comment by stephenholleran** [comment]
@NikoSimisiroglou seems like I can't make you a reviewer on the pull request. Can you just check what I have done and let me know you are happy and then I'll merge it. Thanks.

#126 update lat long description
