### ISSUE TITLE
sample data references sensor_config table, which does not exist in schema

### ISSUE THREAD

**Issue by dave-c-vt** [IEA-Task-43/digital_wra_data_standard#138]
```
ERROR:  relation "sensor_config" does not exist
LINE 71: INSERT INTO sensor_config
```
https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/demo_data/iea43_wra_data_model_demo_data.sql#L71

/tools/iea43_wra_data_model_postgresql.sql has no table called "sensor_config"

it appears line 71 of the demo_data file should be updated to insert into `logger_measurement_config`, see:

[iea43_wra_data_model_postgresql.sql](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/tools/iea43_wra_data_model_postgresql.sql#L375)

and line 110 has a bad reference as well. `sensor_config_uuid` should be `logger_measurement_config_uuid`

https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/demo_data/iea43_wra_data_model_demo_data.sql#L109

and line 129, `instrument_height_mm` should be `instrument_poi_height_mm`

and line 130, `date_from` and `date_to` should be in the `measurement_point_sensor` table, not `sensor`

and line 139, `measurement_type_id` is null, should be `'wind_speed'`

and line 146, `uncertainty` should be `combined_uncertainty`

i'll submit a pull request...

**Comment by stephenholleran** [comment]
Hi @dave-c-vt,

You are absolutely right. This demo SQL insert file is not really complete as it was too tedious to fully match the demo JSON file. I was going to write some code to read the JSON and automatically create the SQL insert statements but obviously I never got around to it. As a result I didn't put much attention into keeping this up to date with the schema.

I see you made the changes though which is greatly appreciated!! I have merged them.

Thanks,

Stephen
