### ISSUE TITLE
[DCC] add version key to schema

### ISSUE THREAD

**Issue by heikowestermann** [IEA-Task-43/digital_wra_data_standard#147]
Currently we don't have a way to identify the schema (version) a dataset is implementing. We should add a key with possibly fixed strings in an enum to the dcc schema. How is this done in the WRA schema?

**Comment by stephenholleran** [comment]
@heikowestermann good idea.
We do this in the WRA Data Model

```

    "version": {
      "type": "string",
      "title": "Version",
      "description": "The version of the IEA WRA Data Model this file is based on. The format of this follows Semantic Versioning with the year and month tagged on after. E.g. 1.1.1-2020.07",
      "examples": [
        "0.1.0-2020.06",
        "1.1.1-2020.07"
      ],
      "pattern": "^([0-9]{1,2})[.]([0-9]{1,2})[.]([0-9]{1,2})-([0-9]{4})[.]([0-9]{2})$"
    },
```

**Comment by heikowestermann** [comment]
Great, thanks Steven! I will add this for the next release. Also I think we need to change the project name, since v1 is already out 😄
