### ISSUE TITLE
[IEC validation requirements] Area of additional members in mast section geometry

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#154]
Some towers have additional members such as feet that need to be taken into consideration for calculating solidity for IEC 61400-12. The influence of those members should be small so I'm not sure we should go into the trouble but by the book those should be included. If we decide it is relevant, we should probably add the are of additional members into the model.

**Comment by abohara** [comment]
@kersting If it is just adding one (optional) field I don't see much of an issue. However, it really does seem like an edge case , and a user can always add a field to the mast section geometry table locally. I could go either way with a slight lean for not doing it right away

**Comment by kersting** [comment]
@stephenholleran and @abohara thanks for looking into this. I came across this problem recently from a tower drawing that I received. The impact in the overall solidity will be small but I'm bringing this up that if one is doing this by the book (and everything done for PPTs should be done by the book because of contracts), we should then include this. I have a handful of additional issues open and I could include that in the mix. I do agree that this needs to be optional. If you're fine with the idea of having an optional field let me know and I'll add to the list of improvements.

**Comment by stephenholleran** [comment]
@kersting are you able to share a screen shot of the particular section so we can understand what it looks like and how we could account for it?

**Comment by stephenholleran** [comment]
Thanks for this @kersting. It gives context and shows what we are talking about.

These could also be called flanges or a base plate.

I don't know how we can capture this geometry as I'd say it could be very different between mast manufacturers. We would need the height and width and just assume it is a rectangular shape when projected onto a face.

The IEC didn't consider it in any of their drawings or calculations. Therefore, I wonder does it make any meaningful impact on the resulting boom length requirement? Are you able to do a comparison of with and without this mast feature included?

Thanks,

**Comment by kersting** [comment]
@stephenholleran Thanks for the feedback. In the example given I calculated the solidity with and without the additional members. The difference was 0.1570% vs 0.1497%. That translated into a Ct of 0.5826 vs 0.5600 and I simulated different boom sizes as multiple of face widths to get the wind speed deficit which is the final goal to determine the level of disturbance in the anemometers. We have the following.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ui901689/AppData/Local/Temp/2/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ui901689/AppData/Local/Temp/2/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Face width | With additional   members | No additional   members | Difference
-- | -- | -- | --
2 | 98.61% | 98.67% | 0.07%
3 | 99.16% | 99.20% | 0.04%
4 | 99.44% | 99.47% | 0.03%
5 | 99.61% | 99.63% | 0.02%
6 | 99.72% | 99.73% | 0.01%
7 | 99.80% | 99.81% | 0.01%



</body>

</html>

As you can see the difference in solidity becomes less pronounced as booms get bigger. The IEC recommends a flow distortion due to the tower to be kept below 99% (or 1% depending on the reference used). For the example above this happens when we cross the threshold of 2 to 3 booms and in that range the difference is roughly 0.04%. One could argue that we don't need such level of precision. As a result, I would recommend, either to not include the area of additional members or include as optional and assume that the area of additional members is always perpendicular to the face of the mast. In that case the user would enter the area directly instead of the dimensions of each individual member.

@stephenholleran and @abohara thoughts?

**Comment by stephenholleran** [comment]
@kersting wrote:
> As a result, I would recommend, either to not include the area of additional members or include as optional and assume that the area of additional members is always perpendicular to the face of the mast. In that case the user would enter the area directly instead of the dimensions of each individual member.

I would go with not including it. If you do include an extra area to cover these flanges then we have the issue if the anemometer **_is not_** mounted at the same horizontal level as the flanges (which is most cases) this extra area shouldn't be included in the calculations.

**Comment by kersting** [comment]
@stephenholleran thanks. @abohara could you please provide your feedback here?

**Comment by kersting** [comment]
@abohara could you please take a look on the discussion? If you agree with Stephen, I'll close this with a comment.

**Comment by stephenholleran** [comment]
@abohara what do you think? I don't think the impact is big enough to consider.

**Comment by abohara** [comment]
Sorry @kersting and @stephenholleran  for my delayed response. I agree with @stephenholleran .
