### ISSUE TITLE
[IEC validation requirements] Sensor body size

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#155]
There is one IEC check that requires the diameter of the upstand to have lower diameter compared to the anemometer body. Currently anemometer body is not capture. I recommend to include the anemometer body size to the sensor table so IEC checks can be performed. I'm curious to hear what you think.

**Comment by abohara** [comment]
@kersting Could go either way. I do wonder if we take all our IEC checks ( sort of unrelated to core WRA) and make one technical discussion out of it. We could then compile all of it into a single push.

**Comment by kersting** [comment]
@abohara this is exactly what I was thinking. I'm coming up with all these IEC related parts because we're tackling all these IEC requirements so they're popping up all together. I think it is a good idea to push them in bulk and discuss them together. I'm also OK if we keep exchanging messages here but it would be more effective to have a dedicated call to all these issues.

@stephenholleran this is section G.2. 

![image](https://user-images.githubusercontent.com/19154103/159768011-acdda888-8e87-4410-ad51-69790e4bd3a4.png)

**Comment by stephenholleran** [comment]
@kersting ok, that makes good sense to include.

I would be inclined to keep the issues separate and simple but we can obviously discuss all of them on one call.

For this one; wouldn't the calibration facility need to be aware of this and so not break the requirement? Then all we need to check is that the anemometer is mounted on the same as that used during the calibration?

**Comment by stephenholleran** [comment]
From our meeting https://github.com/IEA-Task-43/digital_wra_data_standard/discussions/129#discussioncomment-2431888

> HW maybe have a sensor table that captures the classification and also the sensor body diameter along with other static anemometer characteristics. 
> We should include this info in the data model but lets discuss further about an anemometer sensor database.

**Comment by kersting** [comment]
@stephenholleran and @heikowestermann should we continue this discussion? There hasn't been any updates since March. I'm happy to contribute what whatever is necessary.

**Comment by stephenholleran** [comment]
We should include but not sure exactly what to call it. Should it be explicit to an anemometer or a general sensor?

@heikowestermann at the meeting you were talking about a sensor database? Any thoughts on what would this would look like? More importantly, do we (as Task 43) want to maintain a sensor database? I would lean against that but open to the discussion.

**Comment by kersting** [comment]
@stephenholleran I think that there is no reason for a general sensor table because currently only anemometers have classification and requirements in relation to the body size.

**Comment by kersting** [comment]
@stephenholleran should we simplify at this moment and just add the sensor body? If we decide to go in the route of adding a sensor table we could update the model.

**Comment by stephenholleran** [comment]
> @stephenholleran should we simplify at this moment and just add the sensor body? If we decide to go in the route of adding a sensor table we could update the model.

@kersting yeah, I think that is a good approach. Are you able to make the change in a branch and submit a pull request to the dev branch?

**Comment by heikowestermann** [comment]
@kersting @stephenholleran I think that the sensor database should in either case be separate from the model. The database could still be added to the repo as a source of trust. I am still planning to tackle this, but can't say when this will be ready. If anyone else volunteers, I won't object and help out

**Comment by kersting** [comment]
@stephenholleran yes, I can make the pull request to the dev branch.

@heikowestermann as far as the sensor table, if it is separated from the model then I can support in the effort but I would appreciate if you could lead that effort.

**Comment by stephenholleran** [comment]
Thanks @kersting 
I'll close this now.
