### ISSUE TITLE
Missing units for legacy US projects

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#164]
Legacy projects in the US have several measurements using the US customary units (miles per hour, Fahrenheit, etc). Those need to be captured for loggers programmed on those units. I proposed to include some of those units that can be found in such legacy projects and I can be the one modifying the model.

@stephenholleran thoughts?

**Comment by stephenholleran** [comment]
@kersting yep, something we should do. Even knots!

Maybe lets get a complete list to add here first and then implement them?

"mph"
"knots"

We have "deg_F" already.

**Comment by kersting** [comment]
@stephenholleran besides the ones that you have mentioned, I have seen in Hg for pressure which leads us to mm Hg (which I haven't seen yet in resource assessment). We can add as well atm that is not present in the list. If you can think of anything else let me know otherwise I suggest to add the following.

mph, knots, in Hg, mm Hg, and atm.

If you give me the green light, I'll add that.

**Comment by stephenholleran** [comment]
I can't think of any others. 
@abohara thoughts?

**Comment by abohara** [comment]
@kersting @stephenholleran  I don't have any more to add but would support keeping this list open to keep an open thread to track it.

**Comment by kersting** [comment]
@abohara and @stephenholleran I made a commit to dev with the modifications. Thanks.

**Comment by stephenholleran** [comment]
Hi @kersting,

Please don't commit directly into dev. Each issue should be reviewed as a pull request from a branch into dev. That way when we are doing a release from dev to master there is no real review as they were all done for each issue. Commiting into dev means that several different issue end up getting reviewed all at the same time which make it difficult. 

I'll take a look at these now. 

Thanks,

Stephen
