### ISSUE TITLE
Sensor properties

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#17]
I started working in a code to check if a mast is IEC complaint and I realized that we have one property missing. We need to report the diameter of the cups under sensor properties because the IEC standard measures everything from the center of the cups so the the effective sensor height is:

effective_sensor_height = sensor_height - cup_diameter/2

**Comment by joejoeyjoseph** [comment]
decision: choose `instrument_poi_height_mm` -- "point of interest"
add to documentation: 
vane: start from top of the vane
cup: start from center of the cup
sonic: record the height where the wind/air is measured

**Comment by kersting** [comment]
@stephenholleran For me it is all good and we can close it.
