### ISSUE TITLE
Including additional information about diagonal braces in mast_section_geometry

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#170]
@stephenholleran and @abohara Some towers have very different patterns for the diagonal braces. Currently the data model lacks one more piece of information to calculate the solidity. There are 2 possible paths that I can see and maybe even more.

1. Add the length of the diagonal braces.
2. Add information about 2 angles of the braces in one of the patterns.

The first solution seems much simpler because you have way less math to do. Here is what you need for calculating solidity.

- Number of diagonal braces (already in the model)
- Diameter of the diagonal brace (already in the model)
- Length of the diagonal brace
- Face width (already in the model)
- Height of the diagonal braces (already in the model)

Tower specifications usually give all of this information and in the worst case scenario they either give you only the length of the diagonal braces or the height of the diagonal braces. As a result, I propose to add `lattice_bracing_member_length_mm` 

Here is a diagram of the possible patterns.

![image](https://user-images.githubusercontent.com/19154103/168196212-a2f679fd-e5ad-4e1e-b1ec-cf1952a5bf0a.png)

**Comment by abohara** [comment]
@kersting  I am not familiar with naming convention for the 3 patterns you have shown. If there is one, it would make sense to have that as a field (.e.g as `lattice_pattern`), so that the length of the diagonal member makes sense in that pattern context. I think it would be a little preferable then to adding in the angle information.

**Comment by kersting** [comment]
@abohara thanks for the feedback. I could not find any naming convention for lattice patterns. For an IEC calculation the pattern does not matter as long as we have the length and the diameter of the bracing members as well as the number of them. However, if one wants to build a system to show the pattern to the user using an UI such field that you're proposing would be useful.

@stephenholleran what is your opinion on this?

**Comment by stephenholleran** [comment]
I think I need to think about it more. :(

**Comment by abohara** [comment]
@kersting  Is adding `Add the length of the diagonal braces.` sufficient to calculate the solidity given the 3 use patterns ? If that is the case we can add it and close it.

**Comment by kersting** [comment]
@abohara and @stephenholleran yes, adding the length of the diagonal braces and using the variables that we already have is enough to calculate solidity according to IEC 61400-12. 

If one takes case 3, the braces are overlapping; however, the overlapping has minimal impact. I created an example using case 3 with leg of 25mm, braces of 10mm, height of braces of 600mm and face width of 600mm (all values similar to a real tower specification). If one ignores that there is overlapping the solidity is 13.04% and if one does not ignore the overlapping the solidity is equal to 13.02%. For me the difference does not justify additional fields for the case of the crossing members. In summary, the length of the diagonal braces and the variables that we already have will be enough to calculate solidity.

**Comment by stephenholleran** [comment]
Hi @abohara @kersting,

Yeah, I can see how adding `lattice_bracing_member_length_mm` would be useful for these different patterns. We need to distinguish between a horizontal or diagonal bracing member though. This is for the diagonal ones, no need for the horizontal ones. Therefore, I think the name could be `lattice_bracing_member_length_diagonal_mm` in keeping with our other new attribute `lattice_bracing_member_diameter_diagonal_mm`.

@kersting feel free to create a branch off dev to implement this.
