### ISSUE TITLE
lattice_bracing_member_diameter_mm decimal in sql

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#171]
lattice_bracing_member_diameter_mm has the incorrect data type in sql. It should be integer.

**Comment by stephenholleran** [comment]
@kersting I'm not sure if we need to change it to an integer. See other variables that are in this table have decimal. Even the face width which could be argued to be even less likely to be a decimal compared to a member diameter. I'd be inclined to leave it as a decimal as it puts less restriction on users. @abohara thoughts?

![image](https://user-images.githubusercontent.com/25622575/168329473-bdd12e3f-4048-4332-bb90-106f6b872769.png)

**Comment by abohara** [comment]
Yes. I think it should remain a decimal since it technically does not have to be an integer. Something, like the number of members is an integer which seems appropriate.

**Comment by kersting** [comment]
@abohara and @stephenholleran I was probably sleep deprived. I don't know what I had in mind to say that it had to be an integer, I got things mixed together. I'll close this.
