### ISSUE TITLE
Support for Long-Term Corrections?

### ISSUE THREAD

**Issue by sdsmdp** [IEA-Task-43/digital_wra_data_standard#176]
I received the following question:

> Has (or will) IEA Task 43 address long-term correction (i.e., MCP) using the same digital format as the anemometer calibration?

I have requested more information on what use case(s) the individual had in mind and how he envisions model support would help. In the meantime, any comments?

**Comment by abohara** [comment]
@sdsmdp MCP corrections are more of a derived value and dependent on quite a number of factors (such as which long term ref. station, methodology etc.). The task 43 model scope is for actual measurements. So I don't expect it to be on the roadmap anytime soon (my opinion only).

**Comment by stephenholleran** [comment]
@sdsmdp I agree with @abohara, this model is currently for capturing how measurements are configured to give meaning to the column of data. This model would be an input into a correlation.

This might come out of IEC -15 digital reporting work that is currently ongoing. But that would just be reporting and not cover the setup.
