### ISSUE TITLE
Mast section geometry (horizontal and diagonal braces)

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#18]
@stephenholleran: I was working in an tool to check IEC requirements and I found another problem with the data model. Braces can be horizontal or diagonal. It is important to report the number for both of them. If we don't report the direction of the braces (diagonal or horizontal), there is no way to calculate the solidity correctly.

**Comment by stephenholleran** [comment]
Hi @kersting,

That's great you are working on the tool.

For the horizontal bracing member, would it not be included all the time as there is usually a horizontal bracing member at the section joins? To capture worst case.

Maybe past a diagram or photo of what you are talking about?

**Comment by stephenholleran** [comment]
I just noticed you say 

> horizontal **or** diagonal

If there are only horizontal braces (I don't think I've ever seen that) then woud having zero diagonal and always assume there is a horizontal work? (I think a tutorial to explain how to use this part of the data model will be required!)

**Comment by kersting** [comment]
All the towers that I have seen reported only 2 lengths and diameter of braces per section and therefore this distinction that I proposed between horizontal and vertical braces don't make much sense. Perhaps it would be better to have the option to report 2 brace dimensions per section or even 3. One concern that I have is related to IEC's definition of solidity. It is the is defined as the ratio of the projected area of all structural members on the side of the meteorological mast to the total exposed area. The all structural members is the part that concerns me. There are towers that have a foot and even though they are small, in theory it is necessary to account for that even though in practice the effect is quite small. Based on the complexities, I wonder if it would be easier to report only the thrust coefficient of the tower. On that case the analyst would calculate that aside and share the tower drawings via PDF. The thrust coefficient and the boom lengths are the inputs necessary to calculate whether the boom configuration meets IEC requirement.

**Comment by joejoeyjoseph** [comment]
Decision: created a new `lattice_has_horizontal_member` with True/False option

**Comment by stephenholleran** [comment]
@kersting thanks for making that change. Looks good.

Could you also update the json [demo data](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/demo_data/iea43_wra_data_model.json) too to match it?

Thanks!

**Comment by kersting** [comment]
@stephenholleran  Demo data now with example as well.
