### ISSUE TITLE
Obukhov length for stability

### ISSUE THREAD

**Issue by NikoSimisiroglou** [IEA-Task-43/digital_wra_data_standard#182]
Hi, should we add 

1. the Obukhov length to the "measurement_type" or will we put it under "other" 
2. can we add "m" to "measurement_units_id" the Obukhov length used to calculate stability is in meters

**Comment by stephenholleran** [comment]
Hi @NikoSimisiroglou,

How is the Obukhov length measured or is it calculated from other measurements within the logger programme?

**Comment by NikoSimisiroglou** [comment]
Hi @stephenholleran 

It is possible to get both options you describe. You can either set the logger to get the individual parameters needed to calculate the Obukhov length in a post-processing step or you can get the measurement value straight from the logger program itself, similar to how one receives the horizontal wind speed value for example.

Attached is the manual of the Thies 3D US, at page 46 of 116 there is a table that indicated the measured value number one needs to set, when using the user-specific telegram, for a specific parameter to be an output. If you set the measured value of 52 then you will be outputting the Obukhov length as a measurement. 

[4.383x.xx.xxx_US-Anemometer-3D_e.pdf](https://github.com/IEA-Task-43/digital_wra_data_standard/files/8964844/4.383x.xx.xxx_US-Anemometer-3D_e.pdf)

**Comment by abohara** [comment]
@NikoSimisiroglou I think adding `Obukhov_length` to `measurement_type` and adding `m` to `units` should work. In this case is the Obukhov length calculated on sampling interval (e.g. 2sec) or the averaging interval ( e.g. 10m) ? Would you know ?

@stephenholleran I think these request where a param is not directly measured but derived ( at the sampling rate ) is common esp. w Solar. I wonder if we need a parameter in measurement type to note whether a measurement type is derived or directly measured.

**Comment by NikoSimisiroglou** [comment]
@abohara Depending on your purpose you can sample at different sampling rates. Generally speaking 1Hz should be good enough for WRA purposes (might be rightfully challenged on this one, but please note the "generally speaking" part). Nevertheless, if one wants to get smaller vertical heat fluxes they could go down to 20 Hz for example and store the values. The output can also be a 10 min average of the 1Hz data similar to wind speed.
