### ISSUE TITLE
Dead band direction in logger_measurement_config

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#189]
Certain loggers have an option to set the direction that a dead band is pointing. This is independent of the offset value, therefore I think we need to add this otherwise we will fail to obtain the dead band orientation typed in the logger that is applied to the data. I would like to propose the addition of this new parameter to the data model.

**Comment by abohara** [comment]
Thanks @kersting . Make sense to me. Which logger are you thinking of here ?

**Comment by kersting** [comment]
@abohara NRG SymphoniePROs.

@stephenholleran any thoughts?

**Comment by stephenholleran** [comment]
This should be considered in connection with #190

**Comment by kersting** [comment]
@stephenholleran I agree both go hand in hand. Both issues are related to the NRG SymphoniePRO logger. I propose `dead_band_orientation_deg`. @abohara and @stephenholleran what you think?
