### ISSUE TITLE
Should 'height_m' be 'height_agl_m'?

### ISSUE THREAD

**Issue by stephenholleran** [IEA-Task-43/digital_wra_data_standard#19]
`height_agl_m` that is '**height above ground level in meters**' is more descriptive than simply `height_m`.

However, for offshore met masts there isn't a 'a.g.l.' and it could be above mean sea level (a.m.s.l.) or above lowest astronomical tide (a.l.a.t.). How do we account for all of these options?

@abohara

**Comment by kersting** [comment]
@stephenholleran One option is to keep height_m and have another field called reference_height in which it can take a.g.l, a.m.s.l, and a.l.a.t

**Comment by abohara** [comment]
@kersting @stephenholleran 

Not a bad idea... to keep the height parameter as is and then specify what the height is relative. This convention would allow the 'height_referenced_to' be added anytime in the future, so I like that flexibility.

On land, height is something you can measure directly (laser rangefinder etc.), on offshore masts... is the height more of a 'derived' value (sorry I am not quite as familiar with the offshore side)

**Comment by stephenholleran** [comment]
> is the height more of a 'derived' value (sorry I am not quite as familiar with the offshore side)

It is sort of depending on if there was a buoy or tide gauge at the mast. The reference is usually either mean sea level or lowest astronomical tide. These would be measured along the coast at harbors but it is a bit of a guess to transfer this to the mast location. Sea level height can be measured at the mast and then extrapolated to get lowest astronomical tide.
