### ISSUE TITLE
Boom orientation in logger_measurement_config

### ISSUE THREAD

**Issue by peremilandersson** [IEA-Task-43/digital_wra_data_standard#190]
Boom orientation can be specified in some loggers which may be different from the actual boom orientation. The offset in these loggers are then usually in relation to the boom orientation. So in order to correct the total offset applied to the data it is necessary to store this value. Therefore I propose to add a property called `boom_orientation_deg` to the data model under `logger_measurement_config`.

**Comment by abohara** [comment]
Thanks @peremilandersson . Are you able to specify the logger you are thinking of ?

@stephenholleran @kersting thoughts? Make sense to me to include it.

**Comment by kersting** [comment]
@abohara I agree about this one. This is a field in the NRG SymphoniePRO.

**Comment by stephenholleran** [comment]
@abohara I think we need to consider something along these lines alright. We came across it recently too.

@peremilandersson thanks for raising this issue.
Do you think this single new attribute will solve the issue? I remember seeing a graphic (I think from NRG software either cloud or desktop) with a few other variables. I have grabbed the graphic below from https://www.nrgsystems.com/assets/resources/NRG-200M-Wind-Vane-Instructions.pdf which looks like the same thing. This has a Boom Bearing and a Vane Mounting Angle. Your suggestion will cover the "Boom Bearing". Do we need to consider the "Vane Mounting Angle"? We might not as we have `vane_dead_band_orientation` already. Thoughts?

I think we solved it internally by changing the offset we read from the file to be the "total" offset that is applied to the data.

@sdsmdp just to let you know we are discussing this issue. Any thoughts you have would be welcome. :)

---

![image](https://user-images.githubusercontent.com/25622575/193321704-7b540990-1196-474a-82e4-4aa5e997a0b2.png)

**Comment by peremilandersson** [comment]
@stephenholleran thanks for the feedback.

`vane_dead_band_orientation` in #189 will cover "Vane Mounting Angle" in my opinion. Open to hear other thoughts

**Comment by stephenholleran** [comment]
Hi @kersting @peremilandersson,
cc @abohara 

Just to recap the issue and bringing issue #189 into it.

In the NRG SymphoniePRO logger a 'Boom Bearing' and 'Vane Mounting Angle' can be programmed into the logger which will contribute to a 'Total Direction Offset' which is applied to the measured values from the wind vane. Equation is:

> Boom Bearing + Vane Mounting Angle + Offset = Total Direction Offset

Note that the 'Vane Mounting Angle' is respect to the boom and not to True or Mag north. 

Example below from an actual logger file.
![image](https://user-images.githubusercontent.com/25622575/194355324-638e31e6-bf18-4f77-86e0-2a31d3593dbc.png)
240 + 180 + (-0.6035) - 360 = 59.4. The 59.4 is applied to the measured data.

When parsing this type of data file I would recommend not to read the 'Offset' value as we would typically do but to instead read the 'Total Direction Offset' value as this is the offset that is applied by the data logger. As we already capture the actual 'Vane Dead Band Orientation' in the mounting area, we have everything to adjust the data correctly. 

Keeping with this example the 'Vane Dead Band Orientation' would be 59.4 degrees.
If the installer typed the 'Vane Mounting Angle' incorrectly and used 0 instead. This would result in a 'Total Direction Offset' of 239.4 degrees. We have the 'Vane Dead Band Orientation' of 59.4 so 239.4 - 59.4 = 180 which is the error introduced by the installer and what we can automatically correct the data for.

Therefore I do not think we need any additional properties. The reading of this type of file just needs to be changed and then we do not care what the installer typed in or if they made a mistake or not.

However, if you still want to capture this information I would recommend `logger_stated_boom_orientation_deg` to capture the 'Boom Orientation'. If you do this then you would also have to add `orientation_reference` to know whether it is from True North or Mag North. I don't think you can pull this info from the logger file so how will you know which it is? This will introduce an issue as to not knowing whether or not to apply magnetic declination or not.

For the 'Vane Mounting Angle' we cannot just use our existing 'Vane Dead Band Orientation' as they are different things. The 'Vane Mounting Angle' is relative to the boom and not True or Magnetic north. I do not think adding in an additional 'Orientation Reference' of `boom` works as you will already have to have this set to True or Mag within `logger_measurement_config` already. Therefore a name for this would need to be something like `vane_mounting_angle_relative_to_boom_deg`. We probably should be including `logger_stated` to the start.

As mentioned I'm not sure if it is worth it but maybe there are other reasons to add it so please go ahead if you wish to.

**Comment by kersting** [comment]
@stephenholleran thanks for your detailed answer. I had seen the total direction offset and the reason why I avoided, was to not go in the route of using calculated variables. However, for parsing purposes, I think that one could use only the total direction offset field as the logger offset and call for the day. Therefore, I agree closing #189 but perhaps keeping `logger_stated_boom_orientation_deg`. On the other hand, this brings us to an inconsistency because in the same table we have `height_m`, shouldn't we have `logger_stated_height_m`? We don't know what is the reference used by the installer; for example, for an offshore mast or lidar in a platform the reference could be lowest astronomical height or mean sea level. We have a similar problem for the height as we have for the direction. It could be even an onshore lidar standing in a platform of 2m so the height stated in the logger is not the actual measurement height.

cc @abohara and @peremilandersson

**Comment by stephenholleran** [comment]
From meeting https://github.com/IEA-Task-43/digital_wra_data_standard/discussions/129#discussioncomment-3926831 on the 20-Oct-2022 it was decided to include `logger_stated_boom_orientation_deg` in `logger_measurement_config`.
