### ISSUE TITLE
Shouldn't we have date_from and date_to for the mast_properties table?

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#192]
Hello,

In case of a mast collapse that is replaced with the exact same mast but a different serial number, it seems to me that we should have `date_from` and `date_to` in that table `mast_properties`. What are your thoughts? @stephenholleran and @abohara thoughts?

**Comment by abohara** [comment]
@kersting `Mast_properties` does seem like the natural place to handle the dates for this scenarios.

**Comment by kersting** [comment]
@abohara thanks for the feedback. @stephenholleran what do you think?

**Comment by stephenholleran** [comment]
Hi @kersting,

I think the question to ask is if a mast fell down and it was reinstated, is it the same mast and therefore the same measurement location?

As we don't have `date_from` or `date_to` we must have thought at the time of creation that it would be a separate measurement location. It would be very rare and difficult to reinstate a mast exactly as it was previously. In theory it can be the same but in practice I'm not so sure. We had a mast in Ireland that this happened to. We didn't record the mast serial number so we just left the mast details and geometry the same. Unfortunately the 8 anemometers and 3 wind vanes were all put back in different places unbeknownst to us. We had set it up as a continuous measurement location but then had to go back and create a load more measurement points. We should have set it up as a new measurement location.

In saying all that I am not against setting a `date_from` or `date_to`. Just to warn you that there would be a huge amount of duplication of all the mast section geometries as these are children of the mast property. They will all have different serial numbers too but all the other info would most likely be exactly the same. See screen shot of ERD below. Up to you guys, as I said, no problem adding it in.

![image](https://user-images.githubusercontent.com/25622575/203546090-d53843bd-8371-40b1-a94a-3413cabf97ed.png)

cc @abohara

**Comment by stephenholleran** [comment]
Yes, adding it will give the user options so good to add.

I'll do it right now as I am already thinking about it and I am able to spend a bit of time on Task 43.
