### ISSUE TITLE
Issue with SQL when applying 'is optional' and 'cannot be null' from schema

### ISSUE THREAD

**Issue by dancasey-ie** [IEA-Task-43/digital_wra_data_standard#193]
In the JSON schema docs for Logger Measurement Configurations, the 'measurement_units_id' field 'is optional' and 'cannot be null', but if the NOT NULL constraint is applied to the field in the DB, as is done in '/tools/iea43_wra_data_model_postgresql.sql:395' and the 'measurement_units_id' has not been provided, it is not possible to save the record. 

See possible solutions below:
1. Update JSON schema to allow null values by including 'null' in the list of accepted types and in the enum list. (i.e. type: ["string", "null"], enum: [null, .....]]) and update the sql to remove the the NOT NULL constraint when creating the table. Null values will be accepted and the DB will match the json schema.
2. Update the SQL to remove the NOT NULL constraint. This will allow null values in the DB but will not affect the JSON schema, so if the DB was queried the null valued would have to be removed to be compliant with the data model.
3. Update the SQL, to remove the NOT NULL constraint and set the DEFAULT to '-,' which is a string value present in the enum list for 'measurement_units_id'. The DB could be updated to a null be but more likely be left at the default or updated to another accepted enum value. the JSON schema is not changed.

The same issue will occur for calibrations['measurement_type_id'].

**Comment by abohara** [comment]
Thanks @dancasey-ie . I support 2 or 3, since the JSON schema represents the basic schema and SQL is an attempt to duplicate it.

**Comment by kersting** [comment]
@dancasey-ie I support also 2 or 3.

**Comment by stephenholleran** [comment]
Hi All,

I don't think option 2 or 3 are great as option 2 needs some processing on the result to be compliant with the data model. For option 3 the unit '-' is to represent a dimensionless unit and not that the user doesn't know.

Reading option 3 prompted the thought that we don't allow the user to put in something that they don't know. That is, if they don't know the measurement unit, the only option is for them to leave it blank. Another person viewing this doesn't know if the first user just forgot or they actually don't know what the unit should be. 

So a 4th option is to add `unknown` to the enum. The SQL can default to that value. This doesn't impact the data model schema, it is only adding in a new enum which is easy.

**Comment by kersting** [comment]
@stephenholleran excellent point! The problem of not having the units is expected to happen. I think that option number 4 makes sense for the SQL.

**Comment by dancasey-ie** [comment]
After thinking about this more, my proposed options 2 and 3 are not good ideas, and though I agree with @stephenholleran  that a default value of 'Unknown' is better than '-', I think a default value for any optional property is problematic and I would like to  make a stronger case for option 1 - allow 'null' values for optional properties with enum options

a. All other optional properties allow null values. Whether they are strings or numbers, only optional properties with enum lists do not allow null.
b. For all other properties, if it is unknown and optional, then it is just left blank, introducing the 'Unknown' enum is inconsistent with this and may encourage users to start typing 'unknown' into all unknown free text fields, which I doubt is desirable.
c. If a user leaves the property blank and saves, when they query the DB again they will be returned an 'Unknown' value for the property without knowing why. This is confusing for the user.
e. Even if a default value is enforced in the sql schema, this value can still be set to null, unless both a default value and not null constraint is applied. This is unlikely but depending on the developers setting up the DB this also adds additional overhead, complexity and probability of inconsistency.
d. If a user leaves the field blank and saves, the insert payload will still fail validation against the data model schema. The application developer will have to use a custom json schema to allow the null values or write an if statement to apply the default before validating. This opens to doors to inconsistencies across applications and creates overhead for developers. 

We went down the route of setting up a custom json schema to validate the insert payload and allow null values, which is where we came across the the confusing need to include null in both the enum and type properties. If this was handles in the data model schema it would be obvious what is required. Really if an enum list is provided in the type property can be omitted but for consistency across all fields we have kept the type and included the type = ["string", "null"]. See forum thread on optional fields including nulls in enum - https://github.com/json-schema-org/json-schema-spec/issues/258

Suggested change in the schema:
For any optional property with an enum list, include null in the enum list and include null in the allowed types list.

Suggested change in the sql:
Remove defaults and Not Null constraints for all optional properties.

**Comment by abohara** [comment]
@dancasey-ie - Looking at your original comment, you indicated ```_In the JSON schema docs for Logger Measurement Configurations, the 'measurement_units_id' field 'is optional' and 'cannot be null_``` .Looking at the [JSON schema](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/6ef361620d4d881ce51ea3d2c4f706c77106590e/schema/iea43_wra_data_model.schema.json#L963) the `measurement_units_id` is not an optional field (which is why null was not part of the enum). My guess is we failed to include `measurement_units_id` as part of the `required` fields resulting in the [documentation ](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/docs/iea43_wra_data_model-properties-measurement-location-measurement-location-properties-measurement-point-measurement-point-properties-logger-measurement-configuration-logger-measurement-configuration.md#measurement_units_id) indicating that it was optional, which as you can see directly clashes with not being nullable. Specifying, something as being `required` is not part of the core json schema but the automatic doc generator seems to rely in it. So on the context of your original question, adding `measurement_units_id` to the `required` section of `logger_config_measurement` would fix the false impression from the documentation that `measurement_units_id` is `optional`.

However, @kersting , @stephenholleran and @dancasey-ie seem to indicate that perhaps it should be allowed as an optional / nullable property ( and @dancasey-ie's suggestion: `include null in the enum list and include null in the allowed types list` make sense there and is also the same approach used in other fields). Within an organization, keeping this optional make sense ( we do it a lot for this and many other fields). However, if you are receiving data from another company would you like the units to be optional ? If we are going to have guidelines on what is required or not , this use case might be more relevant ( per my 2 c ).

**Comment by dancasey-ie** [comment]
Thanks @abohara, I will leave the business use case of having 'measurement_unit_id' as optional or required to you guys as this is not my area. But as you have detailed, if it is required then include it in the 'required' fields or if it is optional include null in the enum list and include null in the allowed types list.

As mentioned in the original post the same issue arises with  calibrations['measurement_type_id'].

**Comment by stephenholleran** [comment]
During our call on [1-Dec-2022](https://github.com/IEA-Task-43/digital_wra_data_standard/discussions/129#discussioncomment-4285892) it was confirmed that we should follow option 1 for the properties that are not consistent. 

However, the question as to whether or not `measurement_units` is 'required' or 'optional' will be continued in a separate discussion here #200.

**Comment by dancasey-ie** [comment]
Also related, mast_geometry_id type allows null but null is not listed in enum list. 
null should be included in the enum list for mast_geometry_id

**Comment by dancasey-ie** [comment]
Another related issue is the the optional 'date_from' fields in mast_properties and lidar_config. The  fields reference the 'date_from' definition with type 'string' enforced, thus not allowing null.

All other 'date_from' fields are required and so the definition is appropriate.

I suggest that for mast_properties and lidar_config, that the 'date_from' should be defined locally, with type : ['string', 'null']

**Comment by stephenholleran** [comment]
Hey @dancasey-ie,

Thanks for this. You are right if a date_from is not required then it has to have a null option just like the date_to has.

I have made the change to the mast_properties. Nothing is required in mast_properties so no point in having the date_from the only thing required. To avoid breaking changes locally defining it is I think the only option.

Looks like the Date From in Interference Structures **is** required so no need for it to be locally defined.
https://github.com/IEA-Task-43/digital_wra_data_standard/blob/94a1c0e0409ded93af56812f590d4708dba4e5e8/schema/iea43_wra_data_model.schema.json#L1755-L1758

Cheers,

**Comment by dancasey-ie** [comment]
@stephenholleran lidar_configs also has a date_from that is not required. 
Can you define the date_from locally and allow null for lidar_configs?

**Comment by stephenholleran** [comment]
Thanks @dancasey-ie for highlighting.

This applies to `vertical_profiler_properties` too. I have made the updates.
