### ISSUE TITLE
The lidar-measured Turbulence Intensity & Site Description

### ISSUE THREAD

**Issue by SherryXinrui-Li** [IEA-Task-43/digital_wra_data_standard#199]
Hi Stephen, have we discussed the lidar-measured Turbulence Intensity as a variable to consider in the data model?

Also, it might get handy if a site description is added. For example, some questions to consider are: whether the site is in the water or on land; whether the site is close to a wind farm; whether there is any other source of turbulence nearby; and the distance between the site and the source of the turbulence.

**Comment by SherryXinrui-Li** [comment]
@stephenholleran

**Comment by stephenholleran** [comment]
Hi @SherryXinrui-Li,

Yes we have. It is the same measurement from a lidar whether or not it is on land or water so we have it covered off before we even started expanding it for floating lidar. In most cases (and what I would recommend) is that the TI is just another `statistic_type` for a wind speed `measurement_point`. See screenshot below of the example JSON implementation which you can find [here](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/floating_lidar/demo_data/floating_lidar_demo_iea43_wra_data_model.json) in the 'floating_lidar' branch.

![image](https://user-images.githubusercontent.com/25622575/205271468-b1b09542-d947-4dcb-be4b-3e56d9390a10.png)

TI is also listed as an independent `measurement_type` (`wind_speed_turbulence`) so it can be a `measurement_point` all on it's own if you wish to set it up that way.

---

With regards your second question, a "site description" is outside of the scope for this data model. Even for a met mast. The data model represents the met mast, lidar, sodar, floating lidar, solar station as they have been installed on site and how the logger has been programmed. A site description is outside of that. Also, it is an opinion and so changes depending on who describes it, especially if you are trying to document what a source of turbulence might be. This is more of an investigation when analysing the data. This type of information is more appropriate in a high up data model that describes the wind farm and a met mast is part of that other data model. In saying all that, every part of the data model has a `notes` where you can type anything you want. Using the notes at the `measurement_location` would be a good place to describe the surrounding area of the station if you want to put it in somewhere.

The Lat Long is within the data model so plotting it on a map will show you if it is on water or land. Also, if there are neighbouring wind farms is a whole other data model to capture turbine locations, types, hub heights, rotor diameters. Again, this is a higher up data model that we would love to develop.

I hope this helps, let us know if you have any other questions and thanks for asking a question.

Stephen

**Comment by SherryXinrui-Li** [comment]
Thank you for your answers. @stephenholleran
