### ISSUE TITLE
Floating lidar: Logger vs. sensors 

### ISSUE THREAD

**Issue by felixkelberlau** [IEA-Task-43/digital_wra_data_standard#224]
This is about data from floating lidar systems (FLS). Taking as an example wind direction data from 100m above sea_level.

There are several components involved in the data acquisition and processing:
- Lidar (e.g., ZX300)
- Heading source (e.g., Septentrio DPGS)
- Data interface (i.e., Buoy data logger, e.g., FLS OEM's in-house product)

For the meta data file I will create: 
1) "Logger configuration": ZX Lidars, 300M...
2) "Measurement point": Wind direction at 100m, wind_direction, 100, sea_level...
2 a) "Logger Measurement Configuration 1": Logger Slope null, Logger Offset null... Measurement Units: deg... Logger Height 100...
2 a I) "Column Names": WindDirH100, avg...
2 b) "Sensor": Sensor Type lidar...

Although I believe that I understand the definitions of "sensor" and "logger" it is difficult for me to use both unambiguously within the requirements of the data model. Intuitively, I would define:

- Logger: Buoy's Data interface
- Sensors: 1. Lidar 2. Heading source

But this is different from how it is handled in the demo [floating_lidar_demo file](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/demo_data/floating_lidar_demo_iea43_wra_data_model.json), where the lidar is the logger and no sensor is associated with the wind measurements. 

Therefore, my questions include but are not limited to:

- [ ] I) Which is the logger in this example? The lidar or the buoy's data interface or both? I feel it should be the buoy's data interface but where would I then enter the information about the lidar?
- [ ] II) Is the lidar the sensor or the logger or both? A measurement point at a certain height does not have its own sensor, so probably it is the best compromise to call the lidar the sensor for all measurement points. 
- [ ] III) Where is information entered about the heading source? It is a substantial part of the wind_direction estimate. Is is best entered as a second sensor for the wind direction measurement points?  

I appreciate a lot any form of clarification and hope that I didn't miss any instructions that are already addressing this.

**Comment by stephenholleran** [comment]
Hi @felixkelberlau,

Thanks for the questions.

1. **Which is the logger in this example? The lidar or the buoy's data interface or both? I feel it should be the buoy's data interface but where would I then enter the information about the lidar?**
It can be both I would suggest but it is up to you. My view is that the lidar is a logging device, it just so happens to be mounted on a buoy. I would also say that this is the more critical reasons why the buoy is out there in the first place so a wind analyst will want to know how it has been configured and what serial number it is. This information is important so therefore I would put it as it's own entry in the logger_main_config. You can then also add the buoy's logging device which can capture the other measurements. In the demo example there is a lidar and an ADCP in the logger_main_config.

1.  **Is the lidar the sensor or the logger or both? A measurement point at a certain height does not have its own sensor, so probably it is the best compromise to call the lidar the sensor for all measurement points.**
It could be either but I would just pick one. I would recommend putting the lidar as a logger_main_config and not a sensor as there are other important attributes the sensor object doesn't capture for a lidar that the logger would. If it is a sensor you will also end up duplicating the sensor information loads of times. 

1. **Where is information entered about the heading source? It is a substantial part of the wind_direction estimate. Is is best entered as a second sensor for the wind direction measurement points?**
Remind me again what sensor measures the heading? Just a compass correct? That would be connected into the buoy's logging device I would say and be a data column in the file provided? If so, then I would say it is an independent measurement point. If it is not a data column and is just used immediately to correct the wind directions then I'm not sure if there is any point capturing it.

Hope this helps!

Cheers,

**Comment by abohara** [comment]
@stephenholleran 

I think the `lidar` (or the wave buoy) may have to be both i.e. a sensor and a logger. Otherwise, we would not have a clear connection between the measurement and the sensor. Some floating platforms, do have multiple lidars and we will need a clear connection between the data columns / measurements and which device made it.

**Comment by kersting** [comment]
@stephenholleran, @abohara, and @felixkelberlau I agree with @abohara that the lidar needs to be both (sensor and logger). In addition, I think that the buoy can be a logger. In my view the data model is robust enough that we can have two loggers operating in the same measurement location. As @abohara mentioned there are floating lidars with multiple lidars. For those cases they can even generate independent files because each one has its internal logger. 

@felixkelberlau The idea of lidar as a sensor is explained here https://github.com/IEA-Task-43/digital_wra_data_standard/issues/186 and it may help to clarify on why we should treat a lidar as a sensor as well

**Comment by felixkelberlau** [comment]
Thanks to all three of you. I will consider your comments when I continue implementing and come back if anything else is unclear. Thanks again :-)
