### ISSUE TITLE
[SCHEMA] Add "wave_buoy" and "adcp" to measurement_station_type_id enum list

### ISSUE THREAD

**Issue by GTornero** [IEA-Task-43/digital_wra_data_standard#226]
In some offshore wind projects, wave buoys and lone ADCP units are installed independently from floating lidar systems.

It would be useful to have their own categories ("wave_buoy", and "adcp") added to the "measurement_station_type_id" enums in the schema.json file, and the "measurement_station_type" table rows in the SQL schema creation script.

**Comment by stephenholleran** [comment]
Hi @GTornero,

Thanks for making this suggestion and thanks for contributing in yesterday's session.

I think this is a good idea, especially for the ADCP as they can be bottom mounted on their own sometimes. In those cases though some of the data that a metocean analyst is interested in might be beyond the scope of the data model but maybe it won't. 

For the wave_buoy, what measurement would be made by this? I'm assuming the usual temp, pressure, water temp, water pressure, salinity, conductivity and some wave info. 

cc @abohara @kersting

**Comment by GTornero** [comment]
Hi @stephenholleran 
I think you're spot on. Typical wave buoys I've worked with may have some of the following sensors:
- basic weather station (temperature, wind speed, wind direction, humidity, etc)
- seawater sensors (water temperature, salinity, conductivity, etc.)
- downward looking ADCP (current speed and direction at various water depths)
- altimeter (measured water depth)
- wave sensor (wave height, wave direction, peak periods, etc)

**Comment by stephenholleran** [comment]
Thanks for that @GTornero.

I think you have explained a need for it so I have added it to the to do list. It won't be a breaking change too which is great.

Do you want to have a go at implementing it? Just create a branch off the 'dev' branch, make the changes and submit a pull request back into the 'dev' branch. I can do it either. Now that it is on the list we will get to it.

Once we have a good few enhancements, bug fixes, etc. we then do a new release.

Your last comment has highlighted that we are missing an altimeter from the `sensor_type_id` enum. Do you think this is something that should be added or is water depth covered by a different sensor such as the CTD?

Also, if interested we would love if you would join the wind resource working group. I think your experience with implementing the data model on your own could be valuable in how we help others do the same and you are obviously knowledgeable and have good ideas on how to improve the data model. If you are interested I can send you the meeting request. We meet every second Thursday at 5 pm CET for 1 hour.

Cheers,

**Comment by GTornero** [comment]
Hi @stephenholleran. 

I think I should be able to give this a go. I'll try to have something ready in the following weeks.

As for the altimeter vs CTD. I have seen floating LiDAR deployments with a dedicated altimeter, so if it's not a difficult change, we could add it for completeness.

Thank you for the offer to joining the working group. I would be very happy to join as OW's representative. Please send me the meeting request to guillermo.tornero@oceanwinds.com.

Thanks!
