### ISSUE TITLE
Tool to simplify integration with existing processes

### ISSUE THREAD

**Issue by AndyClifton** [IEA-Task-43/digital_wra_data_standard#24]
Love the idea! You might be interested in the [twined tool](https://github.com/octue/twined) that seeks to simplify the process of exchanging data across systems and over organisational boundaries.

It could be a nice way to integrate the WRA data standard with existing processes, rather than requiring folks to completely rewire their processes. See also https://twined.readthedocs.io/ for ideas.

**Comment by stephenholleran** [comment]
Thanks for the suggestion.

@Dynorat @joejoeyjoseph @flrs-edf

**Comment by abohara** [comment]
@AndyClifton @stephenholleran @joejoeyjoseph @flrs-edf 

Looked into the twined tool and it appears to use a similar jsonschema type specification as we do here. The domain of application seems to be more focused on specifying a compute graph or chain steps of an analysis ( sort of a compute pipeline or graph that seem to be standard in ML type analysis these days ) as opposed to describing metadata for a monitoring campaign (though it does it using similar technique ie. json schema). If we move on to generating a schema for the WRA analysis process (as opposed to just a schema for the description of the data ), it certainly seems worth revisiting then. I am ok with closing this comment, unless there is more here.

**Comment by stephenholleran** [comment]
Thanks @abohara!
I'll close this so.
