### ISSUE TITLE
PTH probe as part of the enums in sensor_type

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#247]
WindCubes have a PTH probe to measure pressure, temperature, and humidity all in one sensor. This sensor type is missing under the enums of `sensor_type`. Would make sense to add this?

**Comment by abohara** [comment]
I don't see any issues adding this given that there is a physical sensor in one package that provide all three. The only thing I am not sure is what the device would be called ? PTH (or is that a Vaisala specific acronym)?

**Comment by kersting** [comment]
@abohara and @stephenholleran this `https://www.mdpi.com/1424-8220/22/9/3261` source which is not related to resource assessment also uses the acronym PTS. Vaisala does in their WindCube documentation. The other path is to call it Pressure-Temperature-humidity sensor.

**Comment by stephenholleran** [comment]
Hi @kersting,

Sounds good to add as `PTH`. We already have `CTD` and `ADCP` for offshore.
