### ISSUE TITLE
Adding units to the slope and offset in the calibration table

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#248]
**Is your feature request related to a problem? Please describe.**
Campbell Scientific loggers can be configured in Hz and Volts. If one needs to calibrate the data, it is important to know the units of the slope and offset.

**Describe the solution you'd like**
Include 2 new fields to the `calibration` table. `slope_unit` and `offset_unit`

**Describe alternatives you've considered**
I'm not sure there are alternatives given that if you don't have that information, you'll have to make assumptions about the units based on other tables.

**Comment by stephenholleran** [comment]
Hi @kersting,

Could you please elaborate on the problem? Maybe give an example.

Does a wind analyst care about the slope or offset units so long as the derived measurement units are known? If the resultant measurement units are m/s after a slope and offset has been applied, do we need to know the slope and offset units regardless of the raw measurement been Hz or Volts?

Cheers,

**Comment by kersting** [comment]
@stephenholleran if one is trying to automate the calibration process, and the data is in volts and let's say that the calibration certificate provides the data in hPa, I need to know to save my calibration units, otherwise when I calibrate my data, I won't know the final units of the calibrated data. I'm open to discuss more in the biweekly meeting.

**Comment by abohara** [comment]
@kersting - I do see the concern of how to track the whether the raw measurement is in Hz or Volts, so that the appropriate cal sope / offsets are applied. Partly I assume this is a function of the sensor tech. specs.  However, I wonder without knowing what the raw sensor units are ( which is not part of the data model ) , how would you  know which cal certificates to pick either ? Is there a way this could be implemented internally without modify the data model , partly also for the reasons @stephenholleran points at.

This is a close one for me and could go either way.

**Comment by kersting** [comment]
@abohara the installers provide the units that were programmed in the logger, so we know which units have been applied to the logger. The calibration units are the final units that the user of the data will be working with. In addition, if one is reading a calibration that has multiple units, we may lose track on which is the final unit that your data will have (see the NRG example below).

I can do an internal implementation for this, but I believe anyone who is working in any sort of automation of data calibration will stumble on this problem. 

cc @stephenholleran 

Perhaps we can discuss this in our next bi-weekly meeting.

**Comment by stephenholleran** [comment]
Hi @kersting,

As discussed on the bi-weekly call, https://github.com/IEA-Task-43/digital_wra_data_standard/discussions/129#discussioncomment-9537330, we think this is a good thing to do. Are you able to make a first stab at this?

We also need to include `sensitivity` and we would basically need to copy and paste all the units in the digital calibration certificate over.

Cheers,

**Comment by kersting** [comment]
@stephenholleran thank you for the feedback. Yes, I'll take this one.

**Comment by kersting** [comment]
@stephenholleran shall we add a prefix logger in front of the `slope` and `offset` in the `logger_measurement_config` table?

cc @abohara

**Comment by stephenholleran** [comment]
hmmm, I see your point. In that we have other 'logger_stated..........' properties but not for slope and offset. I'm not sure. It would be a breaking change as it is renaming a property. There is context seen as it is a child of the `logger_measurement_config` so it is distinguishable from the sensor calibrated slope and offset.

I definitely wouldn't be doing it as part of this issue as it is a breaking change. It would need it's own issue card.

**Comment by kersting** [comment]
@stephenholleran that is fine. I can proceed with the change for the calibration. I think we can go either way and if we decide for a change, we can open a new ticket. However, if we do it, I would recommend to release together with other breaking change items.

cc @abohara
