### ISSUE TITLE
Adding device_datum_plane_height and device_orientation_deg to lidar_config

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#254]
@stephenholleran and @abohara 

**Is your feature request related to a problem? Please describe.**
We have noticed installers providing conflicting information when it comes to the height of the platform and device orientation. For example, installers have entered in the lidar configuration a platform height and a device orientation that does not match the physical platform height and device orientation. This is a similar problem as the incorrect sensor height in a logger where the installers may set the height in the logger to 80m but the actual instrument height is 79m.

**Describe the solution you'd like**
My proposal is to add `device_datum_plane_height` and `device_orientation_deg` to `lidar_config` and keep it also in `vertical_profiler_properties`. One would represent the metadata extracted from the parser, the other the metadata from the documentation. We can also add logger_ as prefix of the ones related to the lidar_config.

**Describe alternatives you've considered**
I am not sure it can be done in another way. One could put as part of the `logger_measurement_config`, but I think it would not look good.

**Additional context**
No additional information.

**Comment by stephenholleran** [comment]
Notes from our bi-weekly call https://github.com/IEA-Task-43/digital_wra_data_standard/discussions/129#discussioncomment-9227298

> #254 This is a duplicate to #177. We will close that one. It seems reasonable to record the actual device datum plane height in the Vertical Profiler Properties and then to also record what was programmed into the lidar under the Lidar Config. What was programmed into the lidar and what it actually is may not be the same and they can both change independently over time. Could distinguish the new one in the Lidar Config by prepending "logger_stated_" to them.

I'll put this onto the kanban board too. Anyone want to tackle this?

**Comment by kersting** [comment]
@stephenholleran thank you for the description. I'll take this one.
