### ISSUE TITLE
Data Model to Windog converter

### ISSUE THREAD

**Issue by stephenholleran** [IEA-Task-43/digital_wra_data_standard#31]
Tagging @abohara as I can't pick you from the Assignees list.

How do we get the information contained in the IEA Data Model into Windographer to help an analyst set up Windographer?

I think there are two options:
1. Ideally Windographer themselves create an option to read a IEA Data Model file. @joejoeyjoseph you are going to reach out to UL again to see if this would be a possibility.

1. We write a converter from the Data Model to a Windographer Configure Data Set template file. The Configure Data Set window is shown below along with the paragraph from the Help.

![image](https://user-images.githubusercontent.com/25622575/98278302-4e0a9480-1f90-11eb-8f60-d97393c6319e.png)

![image](https://user-images.githubusercontent.com/25622575/98278576-b2c5ef00-1f90-11eb-8881-00862d764a48.png)

The template file has a file extension of '.wt' and is unfortunately not a simple text file.
![image](https://user-images.githubusercontent.com/25622575/98278918-29fb8300-1f91-11eb-97c6-b7ef3b41dbf2.png)

**Comment by abohara** [comment]
Option 1 would certainly be ideal. However, I suspect it would take a while to happen (if it does at all).

Option 2 certainly would be the preferred route for the short term. However, it does seem to be in a proprietary binary format. 

Option 1/2 could benefit from direct conversation with UL folks. For Option 2, perhaps we can use it as a means of engaging various users who are looking to automate the data in/out of Windographer (may have already done it). I will ask around as well.

**Comment by Dynorat** [comment]
I can reach out to Tom Lambert if you like for a more detailed conversation.


 
 
  On Thu, Nov 5, 2020 at 2:44 PM, abohara<notifications@github.com> wrote:   


Option 1 would certainly be ideal. However, I suspect it would take a while to happen (if it does at all).

Option 2 certainly would be the preferred route for the short term. However, it does seem to be in a proprietary binary format.

Option 1/2 could benefit from direct conversation with UL folks. For Option 2, perhaps we can use it as a means of engaging various users who are looking to automate the data in/out of Windographer (may have already done it). I will ask around as well.

**Comment by stephenholleran** [comment]
> Also, since they have a way of importing from database, all of it may come down to writing a stored procedure.

@abohara That is true. I had forgotten that. I remember looking at that documentation back in 2011 and it could pull back meta data about the column names. So for those that have that setup this Data Model loading into Windographer has no benefit. I would suspect though that there are loads that don't. Even DNV don't use a centralised database to do assessments when they get given data and I know that they sometimes use Windographer to do some analysis. Therefore, even DNV could benefit from a this task.

> I can reach out to Tom Lambert if you like for a more detailed conversation.

@Dynorat based on Jared's comment months ago his connections were actually higher up than Tom to try and get buy in from the whole organisation and that is why @joejoeyjoseph is going to try and reach out to them again. But I suppose this is a very technical thing and Windographer is Tom's so yeah, why not reach out to him directly about this specific topic. So if you could that would be great. Thanks.

**Comment by abohara** [comment]
@stephenholleran @Dynorat I think it would be good to at least have Tom's input (if he is open to it) on the best way to technically solve this data import problem.  I agree it would be beneficial to have a way of exporting in a format that makes it easy to load into Windographer without the SQL license. I am querying other users to see if they have options .

**Comment by abohara** [comment]
@Dynorat Any success reaching out to Windographer folks ?

**Comment by abohara** [comment]
@Dynorat Any success ?

**Comment by stephenholleran** [comment]
@kersting any chance you can pick this up? Thanks.

**Comment by kersting** [comment]
@Dynorat and @stephenholleran I got in touch with Tom and they showed interest but I haven't heard back in a while. Let's keep it open and I'll try again.

**Comment by stephenholleran** [comment]
This has now been implemented by Windographer which is fantastic!
