### ISSUE TITLE
Account for lightening finial (lightening rod)

### ISSUE THREAD

**Issue by stephenholleran** [IEA-Task-43/digital_wra_data_standard#34]
A lightening finial or lightening rod can impact the measurements from a top mounted anemometer. The first thing to know is if a lightening finial is present. The next thing is to know where it is mounted on the mast. Then the orientation of the finial relative to the top mounted anemometer could be worked out.

**Comment by kersting** [comment]
@stephenholleran I propose is_lighting_rod for the Boolean attribute and lighting_rod_orientation_degree for the float. The modification would be on mounting_arrangement table. Please let me know what you think.

**Comment by stephenholleran** [comment]
@kersting @joejoeyjoseph  @sdsmdp @abohara

I have been thinking a lot about where this can fit into the overall Data Model and it is a struggle. I don't think it should fit under `mast_properties` because a lightening finial is not really part of that. It is something that can be added or not and can be moved half way through a measurement campaign. The `mast_properties` is something that doesn't change over time. (If it does it might make more sense to create a new `measurement_location`.) 

`mast_section_geometry` again isn't appropriate because you can have the same mast section all the way up the mast and it is only the top one that would have a finial mounted on it. This same mast section might also apply to sensors mounted on the side of this mast section where the lightening finial is not impactful.

`mounting_arrangement` isn't really appropriate either as this represents how each sensor is mounted on the mast.

So I am reluctantly suggesting creating another table that is linked to the `measurement_point` itself?

Also, instead of calling it `lightening_finial` I am suggesting calling it `interference_structures`. The reason for this is that there are and may be more structures that interfere with measurements. E.g. aviation lights for one and it could be another sensor that is mounted too close or a guy wire. This gives the user options. 

There is no need to put in a boolean _is_lighting_rod_ because if there is no associated row in this new table then it doesn't exist. 

I am suggesting referencing it's position relating to the centre of the mast structure itself i.e. _orientation_from_mast_centre_deg_ and _distance_from_mast_centre_mm_. This can give the position of the interference structure which can then be related back to the sensor position. 

I don't think there is a need to provide a height above ground level as it is related to the measurement point already. If it is at a height not relevant then it wouldn't go in. It is obviously at a height that interferes with the particular sensor measurements.

I am suggesting an attribute _structure_type_id_ which will be an enum to identify whether it is a _lightening_finial_ or _aviation_light_ or _other_.

Below is what I am thinking. Thoughts?

![image](https://user-images.githubusercontent.com/25622575/99585502-56c28800-29de-11eb-8f74-e3dbfa770d35.png)

**Comment by kersting** [comment]
@stephenholleran I think your solution is really good and creating a new table makes sense to me.

**Comment by stephenholleran** [comment]
From today's call we (@kersting @abohara) agreed that this is a good approach.
