### ISSUE TITLE
Mast geometry ID missing

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#37]
@stephenholleran There is one mast geometry ID missing. By the IEC the types are tube, triangular with round edges (the only triangular available so we can leave just triangular), square with sharp edges, and square with round edges. We need to substitute the square with the last two.

**Comment by stephenholleran** [comment]
Hi @kersting,

Just to make sure, are referring to the below which describes the type of mast structure geometry?

```
"mast_geometry_id": {
  "type": [
    "string",
    "null"
  ],
  "title": "Mast Geometry",
  "description": "The type of mast geometry e.g. lattice or pole.",
  "enum": [
    "lattice_triangle",
    "lattice_square",
    "pole"
   ]
```

What are you suggesting to add? `lattice_square_round_edges` and `lattice_square_sharp_edges`?

**Comment by kersting** [comment]
@stephenholleran, Yes that is my recommendation so we can be in line with the IEC terminology. We would replace lattice_square with lattice_square_round_edges and lattice_square_sharp_edges. Also, that will allow for us to calculate the Ct for each tower geometry.
