### ISSUE TITLE
Extra measurement types and units

### ISSUE THREAD

**Issue by stephenholleran** [IEA-Task-43/digital_wra_data_standard#38]
With the addition of remote sensing devices, add in some extra measurement types and units.

**measurement_types**:

- [x] availability -  ZX lidars have a data availability threshold.

**measurement_units**:

- [x] dB - for CNR values

**statistic_type:**

- [x] availability  - similar to 'count' but in percentages

**Comment by stephenholleran** [comment]
Adding:

> With the addition of remote sensing devices, add in some extra measurement types and units.
> 
> **measurement_types**:
> 
> * [ ]  availability -  ZX lidars have a data availability threshold.

- [ ] Dopp Spect Broad

- [ ] CNR

> 
> **measurement_units**:
> 
> * [ ]  dB - for CNR values
> 
> **statistic_type:**
> 
> * [ ]  availability  - similar to 'count' but in percentages

**Comment by stephenholleran** [comment]
Adding

**statistic_type:**

- [ ] ti - for turbulence intensity. THis will allow lidar ti to be linked to the wind speed.



Some of these are part of issue #36 for remote sensing and so are included in pull request #40

**Comment by stephenholleran** [comment]
- [ ] Investigate if any further measurement types, units or statistic types are required for a Geovane https://www.geovane360.com/

**Comment by stephenholleran** [comment]
More to add.

**measurement_types:**

- [ ] elevation / altitude
- [ ] azimuth
- [ ] timestamp

**Comment by abohara** [comment]
@stephenholleran @kersting 
A lot of changes here Stephen. Thanks for the work. My summary 
- 'availability' :  It could mean machine availability (for e.g. sensor offline). Or no data (due to fog or no wind). It could also be defined. Do all remote sensing define availability in the same way ? It seems like a catchall as it currently stands. 
- Not much experience on the solar side but is 'illuminance' and 'irradiance' sufficient to capture GHI / DNI / DHI . Or would those be differentiated better on the sensor properties ? There pyranometer fans may log temperature readings related to keeping the devices cool and how to track those is still a question ? Do you think it is worth grabbing a solar person ?

**Comment by stephenholleran** [comment]
> Do all remote sensing define availability in the same way ? 

No I don't think so. And it might not be just for lidars. I don't have an example though.

> It seems like a catchall as it currently stands.

Availability is tricky because it can mean so many different things. I'm not sure if we can do much better but open to amendments you might suggest.


> Not much experience on the solar side but is 'illuminance' and 'irradiance' sufficient to capture GHI / DNI / DHI . Or would those be differentiated better on the sensor properties ?

Irradiance is sufficient to capture all of those. Illuminance isn't really used but added it in just in case.

I think what you are suggesting is that instead of just solar_irradiance that it should be broken out into:
`global_horizontal_irradiance`
`direct_normal_irradiance`
`diffuse_horizontal_irradiance`

A bit like `horizontal_wind_speed` and `vertical_wind_speed`?

> There pyranometer fans may log temperature readings related to keeping the devices cool and how to track those is still a question ?

I would say that that is just another temperature sensor that happens to be in a pyranometer?

**Comment by abohara** [comment]
Thanks @stephenholleran 

- availability: I agree. We deal with the same issue in turbine analytics. I am ok with it being as is. Either it remain generic-vague or we resolve it to something specific (but avoid the gray). Would you be open to appending something like the following to the explanation: "... This is currently a generic catch-all for all 'availability' like metrics and may be resolved into more specific definitions in future revisions."
```
global_horizontal_irradiance
direct_normal_irradiance
diffuse_horizontal_irradiance
```
This is how I see the data coming in (or some form of it). Just calling all of them irradiance without differentiating (or even clarifying what class of pyranometer) seems like you are 'losing' information ? Again, my intuition is to leave solar stuff out, but leaving 'irradiance' in there can make it sound relevant for solar (and the schema is helpful for that). So I am ok with for now and may be resolve this in another revision (with help from Solar experts). 

```I would say that that is just another temperature sensor that happens to be in a pyranometer?```
Yes. But is it measuring ambient temperature or the temperature of the sensor ?

I think @kersting has the approval on it. Looks good to me.

**Comment by stephenholleran** [comment]
They are good comments @abohara thanks.

Yeah, we should split them up and might as well do it now seen as we are thinking about it.

In the same vain I have split up temperature into `air_temperature` and `temperature` of anything else. Been able to pick out the air temperature will help with automatically calculating the air density.

@abohara if you can approve the pull request now that would  be great. Thanks.
