### ISSUE TITLE
Feature request: metadata for uncertainty quality

### ISSUE THREAD

**Issue by kilojoules** [IEA-Task-43/digital_wra_data_standard#45]
It is possible that different data sets will have different amounts of available detail regarding uncertainty information. Uncertainty point estimates are simple to read but hard to interpret. Entire calibration data sets are more complex to manage but allow for higher-quality uncertainty information. Higher-level metadata could include the type of uncertainty information.

For example, in a data marketplace, where data is exchanged for money, simple point estimates would be very hard to value. Calibration data sets would make it easier for brokers to value data.

**Comment by abohara** [comment]
@kilojoules Thanks ! Uncertainty of a dataset could indeed be helpful in a market place. Currently, the data standard is focused on documenting the details (metadata) of a campaign. Hence, we do have fields for calibration uncertainty (to describe sensor). The overall data set uncertainty (some combination or sensor uncertainty, data recovery etc) I presume is more of a calculation that can be derived from the underlying data stored in this schema. This could be an addon (similar to the IEC compliance calculation in another issue). Is that what you foresee ? or did you have a specific field in mind that may have been missed int the data schema ?

**Comment by kilojoules** [comment]
Uncertainty information often is derived from larger data sources. While using a single number for uncertainty can often be sufficient, uncertainties with large tails, multiple modes, or other unusual structures may require percentile or binned information. It could be interesting to allow for more-advanced UQ analysis with an optional hyperlink leading to a separate calibration data set.

**Comment by kersting** [comment]
@kilojoules Could you please provide a specific example related to resource assessment and this data schema that is under development? A concrete and real application used by the industry would be very helpful for us to understand what you're trying to communicate. In the case of this schema, we have the calibration uncertainties for anemometers defined by MEASNET and used for power performance test under the IEC 614011-1-12 and also used for pre-construction analysis. This framework is very well documented and industry standard. If you cannot provide a case that is well documented, then please provide an example of an application used in resource assessment.

**Comment by stephenholleran** [comment]
Hi @kilojoules

> For example, in a data marketplace, where data is exchanged for money, simple point estimates would be very hard to value. Calibration data sets would make it easier for brokers to value data.

Yes you are correct. However, as @abohara points out the data model is "focused on documenting the details (metadata) of a campaign". It captures how the mast setup was, the facts. 

Coming up with an overall uncertainty includes a lot more than simply the anemometer calibration as @abohara was saying. It also includes how the anemometer is mounted on the mast, how much data was recorded and how good the data recovery was. The data model, along with the timeseries data, has all the information for a market place to derive a "value" for the dataset. I would see the data model as the foundation for a market place to automate the "value" of a dataset and so we are making their life a lot easier. I don't think this is something we should be taking on as that process would first need to be standardized which would be very difficult. I'd leave it to the market place themselves to put their own value on it.

This is unless I have misinterpreted what you are saying?
