### ISSUE TITLE
[schema] make property 'sensitivity' unique

### ISSUE THREAD

**Issue by stephenholleran** [IEA-Task-43/digital_wra_data_standard#49]
When looking for 'sensitivity' through the schema it can find 'Logger Sensitivity' when it could also mean 'Calibration Sensitivity'.
Rename one of them to make it unique.

**Comment by stephenholleran** [comment]
There is more than just sensitivity unique. Slope and offset are also common in more than one place. Take another look at a different way to pull out the correct property name.

**Comment by abohara** [comment]
@stephenholleran From schema design perspective I would consider this a feature than a bug. The ```sensitivty/slope/offset``` in the ```calibration``` table refer to those values in the calibration context, and the ```sensitivity/slope/offset``` in the ```sensor_configuration``` table refer to those values in the logger / sensor calibration context. When you are joining the tables there is a clash in names, but that can easily be resolved by giving them aliases during query, e.g. 'calibration.slope'. Enforcing a unique name for every column across tables (and for other possible tables in the future) is quite the constraint.

Are your issues pertaining from processing them in Python ?

**Comment by stephenholleran** [comment]
@abohara 
> Enforcing a unique name for every column across tables (and for other possible tables in the future) is quite the constraint.

Yes, that wouldn't be possible.
