### ISSUE TITLE
Mounting arrangements properties issues

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#5]
-  [mounting_type_id] I wonder if we should include the case for the booms that are side mounted but incorrectly mounted above the mast. This does not represent good practices and it has a direct effect on the data. 

- [boom_orientation_deg] Some folks use theodolites to get their boom orientation and therefore, I think we should not restrict ourselves to integers.

- [ new field] What about the use of magnetic declination? We could create a calculated field given that we have the dates, and mast location. We could use https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml to generate that information. Users very often make mistakes on that and we can easily automate that. I could take this task. This could even eliminate the need of orientation_reference_id and reference angles always in magnetic which is what is measured on the field.

**Comment by stephenholleran** [comment]
Hi G,

> * [mounting_type_id] I wonder if we should include the case for the booms that are side mounted but incorrectly mounted above the mast. This does not represent good practices and it has a direct effect on the data.

Do you mean like this?
```
 >-<                         >-<             
  |                           |
  |                           |
  |___________________________|
             |\  |
             | \ |
             |__\|
             |\  |
             | \ |
             |__\|
```
I suppose that isn't a goal post layout but how would it be treated differently than a goal post layout?


> * [boom_orientation_deg] Some folks use theodolites to get their boom orientation and therefore, I think we should not restrict ourselves to integers.

Done. And a load of others.


> * [ new field] What about the use of magnetic declination? We could create a calculated field given that we have the dates, and mast location. We could use https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml to generate that information. Users very often make mistakes on that and we can easily automate that. I could take this task. This could even eliminate the need of orientation_reference_id and reference angles always in magnetic which is what is measured on the field.

I think this is a good idea but not sure if we should restrict just yet. As discussed on the call today not all orientation measurements might be referencing magnetic north as some could be done by getting the bearing of two gps points which then reference grid/true north. Also, if we want to set a standard true north might be more appropriate as it would be inline with WGS84 lat longs that we have and it doesn't change like magnetic does. As agreed on the call we should leave it as is for this version 0 and come back to it after some learning from adoption.

**Comment by kersting** [comment]
Hey Stephen,

For the mounting. The configuration that you showed could be one but there is also this one that is even worse. The anemometers are barely on the top of the tower or just below of it. I think this needs to be communicated somehow. Perhaps if one has the anemometer height, tower height, and upstand height, then you can do a check to see if you’re on that situation. The analyst needs a hint that their top instruments are partially obstructed. I guess I’m making things hard to myself now that I realize that this can be actually calculated from the other database properties. Now I’m in brainstorm session. We could create a python code that checks if a mast is following the IEC recommendations for each instrument. This would save the analyst some time and it would tell where are potential problems in the mast. If it makes sense I think I could take that task.








  >-<                     >-<

   |         |\  |         |

   |_________| \ |_________|

             |__\|

             |\  |

             | \ |

             |__\|


Regarding the magnetic declination, I’m fine leaving as it is and put in a future version.

Thanks for looking at my comments.


Best regards,

Gibson Kersting
RWE Renewables Americas, LLC
M +1-512-574-6025

**Comment by stephenholleran** [comment]
> We could create a python code that checks if a mast is following the IEC recommendations for each instrument. This would save the analyst some time and it would tell where are potential problems in the mast. If it makes sense I think I could take that task.

I think that is a great idea. It could be one of the wow factors that could be shown to analysts highlighting the benefits of adopting this. It could be a quick win. If you are happy to take it on then great. A location to place the code might be in this repo's 'tools' folder. If you need some permission for this repo to create a branch to work in just let me know.

**Comment by kersting** [comment]
Hey Stephen,

Just give me one week to confirm that I can take the task. My supervisor is on vacation and I don’t want to give any surprises to him but I think I can take that.

Best regards,

Gibson Kersting
RWE Renewables Americas, LLC
M +1-512-574-6025

**Comment by stephenholleran** [comment]
HI @kersting,

Are you happy for this issue to be closed off?

**Comment by kersting** [comment]
Yes, thanks

Best regards,

Gibson Kersting
RWE Renewables Americas, LLC
M +1-512-574-6025
