### ISSUE TITLE
Scanning lidar & integration of measurements with models

### ISSUE THREAD

**Issue by ClaidheamhAthair** [IEA-Task-43/digital_wra_data_standard#51]
Reading through the JSON Schema, it seem to me scanning lidar is not accommodated, and the schema does not seem suitable for a common representation of wind data from both measurements and models, which would then support the integration of models and measurements into a single object-oriented representation of wind conditions that could then be coupled to other items in the wind power model chain and MDAO (multi-disciplinary analysis and optimisation) process, such as aeroelastic models. 

The measurement object options available for remote sensing seem to have been written only to the extent that these can be described in a manner analogous to met mast measurements, which means the data model will actually restrict measurements by limiting them to what can be described and not accommodating the extended possibilities outwith the capabilities of met masts. This will be crucial where, for example, scanning lidar is compared directly to CFD model predictions of line of sight wind speeds during model validation. 

The schema should be able to distinguish between the location of the measurement device and the measurement itself other than just in terms of height as currently seems to be the case. These device and measurement locations should be treated as distinct with full generality, to accommodate scanning lidar. 

The schema only discusses horizontal and vertical wind speed. It should also accommodate line of sight wind speed. For example, each radial velocity measured by the lidar requires a location of its probe volume in time and space and an orientation of the line of sight. Additional parameters may describe the probe volume, the pulse length and repetition frequency, the integration time for the measurement, and so on. 

The model should support the description of the configuration of the device itself, not just it's location, including details of the scan geometry, the scanning mode (for example sweep-stare or stop-stare), dwell times in any given line of sight, angular velocities and accelerations / decelerations of the beam orientation, and so on. 

The data model should support a common representation of wind conditions between measurements and models, so it should accommodate time varying vector fields. Eventually wind conditions will be represented by a wind object that incorporates both measurements and models, that can interface with uncertainty models based on model validation, to allow the adoption of probabilistic wind turbine design procedures in the MDAO process. It should not be necessary to transform the representation of wind data between wind measurements and the wind models validated using them. The data model should support rather than inhibit progress towards seamless digital integration of the wind energy value chain from turbine design, wind resource and site suitability assessment, operation and life extension. 

The test is whether the wind data model allows the digital twin of a specific well-instrumented turbine to be performed using a digital representation of site specific operational wind conditions that is compatible with the representation of wind conditions used during a design process in which conservatism has been minimised through probabilistic design to reduce costs, so that the digital twin can both predict the productivity and reliability of the wind turbine as accurately as possible pre-construction and ensure that productivity and reliability is achieved post-construction. 

This requires the representation of wind conditions as a digital object integrating measurements and models in a manner compatible with CFD and aeroelastic models. In the simplest example, this would be a cloud of scanning lidar data points in time and space, a CFD model whose predictions of radial velocity matches this as closely as possible, coupled to an uncertainty model representing how well the model fits the data, so that uncertainties can be propagated through a probabilistic design process.

**Comment by ClaidheamhAthair** [comment]
Reading back, that's quite a lot ... something to consider for version 2.0 at least?

**Comment by stephenholleran** [comment]
Hi @ClaidheamhAthair,

Thanks for commenting. 

You are correct that scanning lidar is not considered, yet. We deliberately didn't include it as it is a completely different beast compared to a met mast or vertical scanning lidars. We wanted to get something developed to a pretty good standard for a typical use case. Once that is out there, we can see what the uptake is before spending a huge amount more time developing it for scanning lidars. The version released is v0.1. We think it is comprehensive but I am sure there will be updates before we can get to a v1.0 for met masts.

>  it seem to me scanning lidar is not accommodated, and the schema does not seem suitable for a common representation of wind data from both measurements and models, which would then support the integration of models and measurements into a single object-oriented representation of wind conditions

As I said above, scanning lidar is completely different. The fact that it is similar to a CFD model might mean that a sister data model would need to be developed instead of trying to adopt this one.

> The measurement object options available for remote sensing seem to have been written only to the extent that these can be described in a manner analogous to met mast measurements

Yes, because this is what a wind analyst actually sees and uses to do an energy assessment. They get a data file with 10-min averaged horizontal and vertical wind speeds, wind directions and other info. I realize that there is other data as you mention but currently this isn't used by a wind analyst. It probably will in the future and we can adapt or branch off this data model to accommodate vertical scanning lidars better.

> The model should support the description of the configuration of the device itself, not just it's location, including details of the scan geometry, the scanning mode (for example sweep-stare or stop-stare), dwell times in any given line of sight, angular velocities and accelerations / decelerations of the beam orientation, and so on.

It already captures the information the wind analyst is interested in. Also, the sweep-stare, etc. information is usually hard wired into the device itself so simply knowing the device model can tell the analyst all of that information. The configuration properties are deliberately captured in a separate table which can be expanded when needed.

> The data model should support a common representation of wind conditions between measurements and models, so it should accommodate time varying vector fields. Eventually wind conditions will be represented by a wind object that incorporates both measurements and models, .................................

Yeah, that would be great. But we have to start somewhere.

**Comment by ClaidheamhAthair** [comment]
Hi Stephen

Thanks for responding, sorry if I came across a bit like I had a bee in my bonnet about this. You're right, we have to start somewhere and the use case you have identified is of course the one most likely to encourage adoption, which is absolutely key.

I realise I possibly raised a bit of an "everything" issue. I'd be delighted if I could take a step back, mull things over, and then come in with perhaps a more focussed and concrete proposal for the next version.

Thanks for an excellent presentation earlier today. I think it would be well worth while looking at how data exchange in wind resource assessment constitutes a use case of the Open Energy platform I mentioned, as I think it's getting a big push and lots of buy in, and the data model is, I think, a great fit, as Open Energy is all about discoverable, easily shared data. I recall the analogy raised during early discussions: it's like when everyone was using a variety of different electrical appliances, but they all had different kinds of plug. Something as simple as standardising the plug unlocked a huge amount of value and eliminated a huge amount of friction. I suppose we are concerned with making it as easy as possible to plug tools into data, just as they were plugging appliances into electricity.

Warm regards

Peter

________________________________

**Comment by stephenholleran** [comment]
Thanks @ClaidheamhAthair, we would love to have you come on a call with us. We can pencil in the 11th March if you are available?

**Comment by abohara** [comment]
@ClaidheamhAthair would be great to have you come chat at our meetings. Perhaps help identify what a reduced set of variables are so we can get up and running.

**Comment by ClaidheamhAthair** [comment]
Hi @stephenholleran @abohara a call on 11th March sounds ideal, thanks, let's talk then

**Comment by stephenholleran** [comment]
Hi @ClaidheamhAthair, I don't think I sent you the meeting invite as I don't have your email?

If you are still available for the call today please send me your email and I'll forward the invite. My email is stephen@brightwindanalysis.com

Cheers

**Comment by ClaidheamhAthair** [comment]
Hi Stephen

Sorry I didn't get back to you earlier. No, I didn't receive an invite, but would still like to attend - drop me a line at my work email at ***@***.*** and let's arrange something.

Warm regards

Peter

________________________________

**Comment by abohara** [comment]
@stephenholleran Did we invite @ClaidheamhAthair ? We can close this otherwise ?
