### ISSUE TITLE
[DCC] place_of_calibration could be ambiguous

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#53]
@stephenholleran I am afraid that place_of_calibration could be ambiguous. There is one calibration organization out there that operates in 2 countries. What if a calibration organization builds two tunnels in the same country? It is very unlikely that a calibration organization would have 2 tunnels in the same city. Should we change from place_of_calibration to city_of_calibration?

**Comment by ponce10** [comment]
@Gibson: Actually there are some institutes that have more than one wind tunnel. However naming of those is not standardised. Probably would be good to have something like place of calibration and internal designation for the sake of completeness. However for data exchange purpose that might to be crucial.

**Comment by kersting** [comment]
@ponce10 The idea of the place_of_calibration is to address the fact that some institutions have multiple tunnels. As far as I'm aware the institutions with multiple tunnels, have their tunnels in different countries. Is that correct? Are you aware of tunnels from the same institutions in the same country?

**Comment by ponce10** [comment]
@gibson: In fact DWG has more than 1 tunnel in 1 location. You are right. Most have only one tunnel (like us), but the format shall be open to collect all relevant information in the certificate.

**Comment by kersting** [comment]
For me the location is more important for traceability. For example, I want to know if my anemometer was calibrated in tunnel A vs tunnel B because tunnel A and B have a different geometry. That is the reason why place_of_calibration would be important because it would help in the traceability. If there is another feature that we can use to keep that traceability then I think we should consider.

**Comment by heikowestermann** [comment]
In my opinion `place_of_calibration` should be a unique string identifying the location or in my case multiple wind tunnels. In my current example dataset I use the following string in the calibration certificate (demanded by ISO17025) and the data export: _"Wind tunnel 2 of Deutsche WindGuard Wind Tunnel Services GmbH, Varel"_. This identifies the location and the wind tunnel. 
I think `place_of_calibration` leaves enough room to define these unique strings and is not too restrictive, while something like `city_of_calibration` would not allow to differentiate between the individual calibration tunnels.
@kersting i think this is what you intended, right? Maybe the description of  `place_of_calibration` can be changed to accomodate the 'uniqueness' of the string?

**Comment by kersting** [comment]
@heikowestermann I like your proposal. If the information is available in the calibration certificate that would work very well. Is that information available usually in calibration certificates?

**Comment by heikowestermann** [comment]
@kersting To be sure I looked it up again: ISO 17025 (the accredited calibration lab standard) states that "the location of performance of the laboratory activities [...]" has to be in each report. Since all anemometer calibrations need to be accredited, I think it's safe for us to assume that all labs include such a statement. This doesn't necessarily mean that the individual wind tunnels are named, but at least this information can be directly translated to `place_of_calibration`.

**Comment by abohara** [comment]
@heikowestermann @kersting It seems may be we should have a ```tunnel_id``` since that is separate. Right now the ```place_of_calibration``` seems to be a serving dual purpose of tracking the physical address of the labs and the tunnel number. That way if for some analysis we do need the tunnel number, we don't have to relying on parsing a string like "Wind tunnel 2 of Deutsche WindGuard Wind Tunnel Services GmbH, Varel" to extract that information (especially since the text format could vary between report / labs) ? That way the ```place_of_calibration``` could only point to the location of the calibration facility ( may be it could reworded).

**Comment by kersting** [comment]
@abohara I like your proposal but we need to make sure that the number of wind tunnels is not so big. There are not many calibration institutes out there though. Would the calibration institutes would be responsible for providing tunnel_id and place_of_calibration?

**Comment by stephenholleran** [comment]
@abohara @kersting 

I think for us, now, I agree with @heikowestermann 
> I use the following string in the calibration certificate (demanded by ISO17025) and the data export: "Wind tunnel 2 of Deutsche WindGuard Wind Tunnel Services GmbH, Varel". This identifies the location and the wind tunnel.
I think place_of_calibration leaves enough room to define these unique strings and is not too restrictive

'place_of_calibration' is good enough for us now.

I would defer this to the possible Digital Certificate Standard to capture if a tunnel id would be required. It may be just a case of defining what 'place_of_calibration' means. In that, it should identify the actual tunnel/device/equipment used in carrying out the calibration. Once they sort it out we'll just amend our schema and pull from that.

**Comment by stephenholleran** [comment]
From meeting:
@kersting to check if there are calibration facilities that do not have a unique string in 'place_of_calibration'.

**Comment by kersting** [comment]
@stephenholleran I looked at calibration certificates of DWG, SOH, IDR, Ammonit, and ProfEC Ventus. All of them have and address but only DWG and ProfEC Ventus use the definition place of calibration. If we can confirm with the calibration institutions that the address matches the place of calibration then we're fine. We should discuss this topic in the next meeting.

**Comment by stephenholleran** [comment]
> @stephenholleran I looked at calibration certificates of DWG, SOH, IDR, Ammonit, and ProfEC Ventus. All of them have and address but only DWG and ProfEC Ventus use the definition place of calibration. If we can confirm with the calibration institutions that the address matches the place of calibration then we're fine. We should discuss this topic in the next meeting.

@kersting that is not great. Seen as place of calibration is in the ISO standard I would have hope it would be there. I checked an Ammonit Wind Tunnel one and I did find it. It was on the second page so not obvious when there are other descriptions on page 1. See screen shot below.

Would SOH, IDR have that info in other places on the cert?


![image](https://user-images.githubusercontent.com/25622575/110113711-63ab9180-7dab-11eb-8b56-e451f3efe0db.png)

**Comment by ponce10** [comment]
> > @stephenholleran I looked at calibration certificates of DWG, SOH, IDR, Ammonit, and ProfEC Ventus. All of them have and address but only DWG and ProfEC Ventus use the definition place of calibration. If we can confirm with the calibration institutions that the address matches the place of calibration then we're fine. We should discuss this topic in the next meeting.
> 
> @kersting that is not great. Seen as place of calibration is in the ISO standard I would have hope it would be there. I checked an Ammonit Wind Tunnel one and I did find it. It was on the second page so not obvious when there are other descriptions on page 1. See screen shot below.
> 
> Would SOH, IDR have that info in other places on the cert?
> 
> ![image](https://user-images.githubusercontent.com/25622575/110113711-63ab9180-7dab-11eb-8b56-e451f3efe0db.png)

The ISO 17025 requires the following: "the location of performance of the laboratory activities, including when performed at a customer facility or at sites away from the laboratory’s permanent facilities, or in associated temporary or mobile facilities;"

Thus all calibration certificates must have the info where the sensor is calibrated. However for some sensors it is not that relevant as it is for others and how it is implemented and put into the calibration certificate depends on the accreditation body and sometimes even on the supervision staff from the accreditation body.

**Comment by stephenholleran** [comment]
Thanks @ponce10, very useful.

@kersting going by this place of calibration must be there. Are you able to check SOH and IDR again to make sure?

Also, just an FYI; this:
> and sometimes even on the supervision staff from the accreditation body

is what worries us from a digitalisation point of view and is something we think a collaborative approach to a digital calibration certificate could help us with.

**Comment by kersting** [comment]
@ponce10 and @stephenholleran I'm sorry for my oversight on the place of calibration for Ammonit wind tunnel. I looked again on SOH (North America only) and IDR and I confirm that place of calibration is not there.

**Comment by ponce10** [comment]
Do not over interpret the statement on accreditation body staff. The differences are small.

> Thanks @ponce10, very useful.
> 
> @kersting going by this place of calibration must be there. Are you able to check SOH and IDR again to make sure?
> 
> Also, just an FYI; this:
> 
> > and sometimes even on the supervision staff from the accreditation body
> 
> is what worries us from a digitalisation point of view and is something we think a collaborative approach to a digital calibration certificate could help us with.

**Comment by kersting** [comment]
@ponce10 SOH has the address but nothing about place of calibration. For IDR they have test laboratory which would be a substitution for place of calibration so I guess for IDR is just a wording problem.

**Comment by stephenholleran** [comment]
From meeting:
It was decided to improve the description in the Schema for now.
It is hoped that a digital calibration group could define place_of_calibration to be a unique identifier for a wind tunnel or place that will be part of their standard.

**Comment by stephenholleran** [comment]
It was decided that `place_of_calibration` will link to `wind_tunnel_id` in the digital calibration certificate.

Update WRA Data Model description to state this.
