### ISSUE TITLE
[schema] suggest remove the `additionalProperties: false` for the header info

### ISSUE THREAD

**Issue by stephenholleran** [IEA-Task-43/digital_wra_data_standard#55]
I am proposing removing the `"additionalProperties": false` for the header info in the schema. This restricts any other properties that someone wants to write in. Seen as this is for the header information (as shown in the snippet below) it doesn't impact on the schema itself.

```
{
  "author": "Stephen Holleran",
  "organisation": "brightwind",
  "date": "2020-06-07",
  "version": "0.0.0-2020.07",
  "plant_name": "A Name of Wind Farm",
  "plant_type": "onshore_wind",
  "measurement_location": [{
       ...................,
       ...................
```

The use case in my particular situation is for BrightHub. We would like to attribute the owner of the data in the data that is downloaded from BrightHub either from the UI or API. Adding properties such as `"source": "Company name"` is what we would like to do.

I am sure there are other properties other organizations would want to put into the header for their own use cases and so I think this is a bit restrictive. It could be other wind farm information.

**Comment by heikowestermann** [comment]
I have been thinking about the restriction of additional data for my calibration certificate schema as well and I think there is not much gained in restricting meta-data, so I am in favor of flipping false to true. Beeing restricitive keeps everything nice and tidy but the downside would be that potential adopters can get scared away.
