### ISSUE TITLE
sensor_type_id for geovane

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#58]
@stephenholleran Given that the geovane is gaining more acceptance in the wind industry, we would need to define what is the sensor_type_id for it. We could put under other but I think we should give a propoer id to it. Also, I believe geovane is a commercial name for the device. What are your thoughts?

**Comment by stephenholleran** [comment]
Hi @kersting,

Yeah, sensor_type_id like 'anemometer'. We have it's measurement_type_id which is 'true_north_offset' and units of 'deg'. We are missing sensor type. https://github.com/IEA-Task-43/digital_wra_data_standard/issues/38#issuecomment-755744199

I'm not exactly sure what it should be? It is measuring the offset from True North or you could say a direction. Therefore, is it a compass?

I have emailed Kintech to ask.

**Comment by stephenholleran** [comment]
From meeting:
Investigate using compass_true and compass_magnetic.

**Comment by stephenholleran** [comment]
Sorry @kersting @abohara @heikowestermann @flrs-edf this is a bit long but there is a conclusion (if you all agree).

Some definitions of 'compass'

https://en.wikipedia.org/wiki/Compass
> A compass is a magnetometer used for navigation and orientation that shows direction relative to the geographic cardinal directions (or points)......These numbers allow the compass to show magnetic North azimuths or true North azimuths or bearings, which are commonly stated in this notation. If magnetic declination between the magnetic North and true North at latitude angle and longitude angle is known, then direction of magnetic North also gives direction of true North.


https://www.merriam-webster.com/dictionary/compass
> 3 a: a device for determining directions by means of a magnetic needle or group of needles turning freely on a pivot and pointing to the magnetic north

> 3 b: any of various nonmagnetic devices that indicate direction


https://dictionary.cambridge.org/dictionary/english/compass
> a device for finding direction with a needle that can move easily and that always points to magnetic north
 

https://www.dictionary.com/browse/compass
> an instrument for determining directions, as by means of a freely rotating magnetized needle that indicates magnetic north.

From my reading of this a compass can be any device that tells direction but I think it is safe to say that in common language it is considered a magnetic compass. 

Non-magnetic compasses are Gyrocompass and GPS receivers used as compasses. They give direction relative to True North. Their names are not defined by what North they refer to but by the technology used i.e. gyroscopes and GPS. The Geovane uses the sun (and a GPS to get its location but that bit is just used to calculate the theoretical azimuth) measuring it's azimuth to then work out True North. Therefore I am thinking of `solar_compass`?

So I Googled 'solar compass' and sure enough back in 1985 a guy called William Austin Burt developed the [Burt's solar compass](https://en.wikipedia.org/wiki/Burt%27s_solar_compass) which used the exact same methodology as the Geovane is using now. 

Also definition:
https://www.britannica.com/technology/solar-compass
> Solar compass, also called Sun Compass, type of navigational instrument that uses the position of the Sun to establish bearing.

FYI, there is an [Astrocompass](https://en.wikipedia.org/wiki/Astrocompass) but this uses other astronomical bodies to find True North using the same principals as the solar compass.

So, I think it is technically appropriate to assign the Geovane as a `solar_compass` sensor type?

**Comment by flrs-edf** [comment]
Thanks for this interesting in-depth research, @stephenholleran! To me `solar_compass` sounds like the way to go!

**Comment by kersting** [comment]
@stephenholleran I agree with Florian.
