### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by Dynorat** [IEA-Task-43/digital_wra_data_standard#6]
Recommend a group discussion on which license to use. 

Recommend BSD 3 Clause or MIT

https://choosealicense.com/no-permission/

**Comment by stephenholleran** [comment]
Hi @Dynorat,

Yes, a license is needed for sure.

When you say BSD 3 Clause I am assuming you mean this one https://choosealicense.com/licenses/bsd-3-clause/ 
and not this one 
https://choosealicense.com/licenses/bsd-3-clause-clear/

**Comment by stephenholleran** [comment]
Extract from https://opensource.stackexchange.com/questions/217/what-are-the-essential-differences-between-the-bsd-and-mit-licences

> So what both the 2-clause BSD license and the MIT license have in common are:
> 
> - Permits use
> - Permits redistribution
> - Permits redistribution with modification
> - Provision to retain the copyright notice and warranty disclaimer
> 
> In addition the MIT license also explicitly allows:
> 
> - merging
> - publishing
> - sublicensing
> - selling
> 
> However, all these freedoms are implied by the BSD license, because all these activities can be considered "use" and/or "redistribution" of the software.
> 
> The practical differences between the 2-clause BSD license and the MIT license are marginal. Which one to pick is mostly up to personal taste. Especially considering that both licenses are considered compatible, so you can take code under one license and use it in a project under the other, as long as you keep the license text around.

Between these two I would go with the MIT one. However the choice is between the BSD 3-clause and MIT.

The difference between the BSD 3-clause and the BSD 2-clause is this extra clause which requires written consent from the copyright holder to promote derived products:

> Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

It would be good to be acknowledged for this work and would help promote this group and the data model itself. This extra clause doesn't require this group to be acknowledged but requests permission to be acknowledged. Therefore there is a barrier for people to acknowledge this group which I don't think is good. Therefore, I'd go with the MIT license.

**Comment by stephenholleran** [comment]
After a discussion on 2020-08-13 it was decided to go with the BSD 3-clause subject to some legal clarifications and confirmation from some members.

**Comment by stephenholleran** [comment]
The following have agreed to the BSD 3-clause license:

- RWE @kersting
- EDF @flrs-edf 
- Brightwind @stephenholleran 
- NRG @sdsmdp
- Altosphere @abohara
- NREL @Dynorat @joejoeyjoseph 

I will write a Slack msg asking if anyone else in the group strongly disagrees with this license.
