### ISSUE TITLE
sensor_config table naming

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#68]
@stephenholleran I'd like to bring up a point related to the sensor_config table. After some internal development it became confusing for the DB developer that sensor_configuration also applied to remote sensing devices. Based on that I'd like to ask if it makes sense for us to just call it measurement_configuration. This would relate better with measurement_point and it would be less confusing if you're dealing with remote sensing devices.

**Comment by stephenholleran** [comment]
Hi @kersting,

I agree the `sensor_config` name is not the best even for a met mast. It is "The sensor configuration that is programmed into the logging device." It should possibly be called something like `logger_config` or `logger_sensor_config`. We already have `logger_main_config` for the main logger configuration settings.

I see the logic in calling it `measurement_config` as it links to the measurement point but is that anymore obvious that this is the configuration settings that are programmed into the logger?

Maybe what is more appropriate is `logger_measurement_config`? But that is long but maybe that is ok?


The **other main** thing to consider here is that this is definitely a breaking change. Do we want to make breaking changes this early in the release or does it matter? I think this is the first question we need to ask ourselves @Dynorat @abohara @sdsmdp @heikowestermann @flrs-edf

**Comment by sdsmdp** [comment]
What about `programmed_sensor_config`? Sadly, it is not any shorter. But does that capture what you were trying to describe, @stephenholleran ?

**Comment by flrs-edf** [comment]
I am not worried so much about the length or the introduction of a breaking change at this point.

**Comment by stephenholleran** [comment]
Thanks @sdsmdp 

> What about `programmed_sensor_config`? Sadly, it is not any shorter. But does that capture what you were trying to describe,

The point @kersting is making is that a lidar unit doesn't have a "sensor" up at 100m and so 'sensor_config' is misleading when dealing with just lidars. So a name with sensor wouldn't be appropriate.

I would be interested to hear what do you think about:
> Do we want to make breaking changes this early in the release or does it matter?

**Comment by kersting** [comment]
I like logger_measurement_config better because I think we should remove the word sensor from the table name to avoid confusion with remote sensing devices. I don't see the breaking change as a big problem right now.

**Comment by sdsmdp** [comment]
Sorry, I guess I didn't read enough of the thread. Given the clarification, I agree with `logger_measurement_config` or perhaps consider `programmed_measurement_config`. Either way, I think it will be clear enough that we are configuring how to make a measurement, whether via a sensor or a range gate at the described height.

I have no reason to be concerned about a breaking change this early in the game. You, @stephenholleran, and @flrs-edf, and @kersting are probably the key users at this time. If you can absorb I think we are okay. At later stages, we could talk about migration and deprecation strategies to help mitigate the overhead of breaking changes, but I don't think we need to take that on until the installed base using the model grows further.

**Comment by abohara** [comment]
@stephenholleran @kersting 

The proposed changes sound reasonable (agree breaking changes are not a concern). However, there is a host of other naming oddities that I think warrant a revisit. For e.g. may be a 'measurement_point', should be a `measurement_stream` given many measurements are not oriented towards points and if measurement_point table should have more distinguishing properties beside height/measurement type (i.e. orientation). I recall Gibson had a few others as well. All these naming considerations would benefit from consideration together since they seem to be arising out of some patterns we are assuming implicitly. If there is time in one of the upcoming meeting, hashing these over a discussion would be helpful.

**Comment by stephenholleran** [comment]
During meeting 25-Mar-2021 we agreed that logger_measurement_config is good to go with.
