### ISSUE TITLE
Review logger configs

### ISSUE THREAD

**Issue by stephenholleran** [IEA-Task-43/digital_wra_data_standard#7]
Hi @sdsmdp,

Could you review the logger configuration, please? The easiest way is to just review the documentation and write any issues you have in this issue.
https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/docs/iea43_wra_data_model-properties-measurement-location-measurement-location-properties-logger-configuration-logger-configuration.md

Thanks,

Stephen

**Comment by sdsmdp** [comment]
Hi, @stephenholleran. This was another good way to remind me of my task. Thanks.

## Feedback

* `logger_model` - the examples given suggest we are looking model name, not a model number; a) can you confirm, and b) suggested changing this to `logger_model_name' to make it even more clear
* `logger_serial_number` - some manufacturers (e.g., NRG) include the logger model number in the serial number output by the logger (e.g., 820699999, where 8205 is the model and 99999 is the s/n); I assume we'll just take whatever value normally outputs whether it's a compound value like this example or really a true s/n only, but just wanting to confirm (if we only want the true s/n, then we may want to provide further guidance in the documentation)
* `date_from` & `date_to` - when we say "It is advised that timezones not be used,' I take this to mean that we are expecting local time; is this wise? Generally data should be stored as UTC, but when transmitting as local time, there will be no way to do that correctly. To my knowledge loggers either output in UTC anyway (can use the 'Z' designator with nothing after it), or in local time, but the time zone is known and so should be included (e.g., <time>±hh[:mm])

<more to follow>

**Comment by stephenholleran** [comment]
> Hi, @stephenholleran. This was another good way to remind me of my task. Thanks.
> 
> ## Feedback
> ### 2020-08-12
> * `logger_model` - the examples given suggest we are looking model name, not a model number; a) can you confirm, and b) suggested changing this to `logger_model_name' to make it even more clear

Changed to 'logger_model_name'.

> * `logger_serial_number` - some manufacturers (e.g., NRG) include the logger model number in the serial number output by the logger (e.g., 820699999, where 8205 is the model and 99999 is the s/n); I assume we'll just take whatever value normally outputs whether it's a compound value like this example or really a true s/n only, but just wanting to confirm (if we only want the true s/n, then we may want to provide further guidance in the documentation)

Yeah, we'll just take the compound. Not too worried about the model number included.

> * `date_from` & `date_to` - when we say "It is advised that timezones not be used,' I take this to mean that we are expecting local time; is this wise? Generally data should be stored as UTC, but when transmitting as local time, there will be no way to do that correctly. To my knowledge loggers either output in UTC anyway (can use the 'Z' designator with nothing after it), or in local time, but the time zone is known and so should be included (e.g., ±hh[:mm])


We have had so many problems with timestamps having timezones in them. They just cause serious confusion and inconsistencies. The timestamps outputted in a data file don't have timezones but in the logger settings we have the timezone or UTC offset recorded. If a logger is set to Eastern time but then someone in Mountain time is creating or editing this data model the data file has a timestamp that doesn't have a timezone but then the 'date_to' does have a timezone can you tell me what will happen? I could there been a 6 or 7 hour time difference between the two depending on daylight saving. We avoid them but if you can tell me a much more robust way of doing it that would be great.



> ### 2020-08-13
> * `encryption_pin_or_key` - I can't speak for certain for other logger manufacturers but I need to share that this value is not something NRG would ever put in a file and pass around (certainly not w/o further encrypting the value or encrypting the JSON file itself while in transit); therefore optional is good, but we might consider further encryption as a way to increase use of this attribute. The other consideration is who the recipient of the file may be. Owners should certainly have access to an encryption pin or key. They also should be in control of who else they share it with (or, again, we defeat the purpose). That suggests to me that owners need an option to enable/disable this attribute on JSON creating. When manually creating the JSON file, this option is inherent. When doing so programmatically (e.g., from the logger directly or from some intermediate conversion service), this would seem a requirement for those scenarios).

I have created a separate issue to remind us of this for when we create a UI or conversion software or whatever.

**Comment by stephenholleran** [comment]
Hi @sdsmdp,

Are you happy to close this off or do you want to review some more?

**Comment by stephenholleran** [comment]
@sdsmdp I brought up the timezone question on the group call today. For this version it was thought best not to put any restrictions on it yet. A compromise was to change the text to something like this:

> If a timezone is used, it is essential that this timezone is the same as the logger timezone.

How does this sound to you?

**Comment by kersting** [comment]
@stephenholleran 

logger_oem_id: Should we have other in the options? We could restrict to that selection and if there is another logger manufacture we could just update the schema. For me this keeps it tighter and serves as a validation as well.
logger_name: Could you please remind me what is logger name?
sampling_rate: In my point of view this should be an integer because it is already in seconds.

**Comment by stephenholleran** [comment]
Hi @kersting,

> logger_oem_id: Should we have other in the options? We could restrict to that selection and if there is another logger manufacture we could just update the schema. For me this keeps it tighter and serves as a validation as well.

I think the thinking was that as this is a first version we don't want to restrict it too much as it will disenfranchise people if they can't find their logger. I do agree that it would be better to restrict it but for this first version I think we discussed leaving 'other' in there as an option.

> logger_name: Could you please remind me what is logger name?

I have added '(or mast name)' to the description.
```The logger (or mast name) name assigned to the logger in the logger programme.```

> sampling_rate: In my point of view this should be an integer because it is already in seconds.

Done
