### ISSUE TITLE
Move objects to definitions

### ISSUE THREAD

**Issue by heikowestermann** [IEA-Task-43/digital_wra_data_standard#71]
While working on the schema I wanted to validate my calibration dataset against the 'calibration' object inside the schema. Currently this seems to involve multiple steps into the schema. Here is a python example:
`wra_schema['properties']['measurement_location']['items']['properties']['measurement_point']['items']['properties']['sensor']['items']['properties']['calibration']['items']`
For the schema as a whole this is not a problem. The need for subsets of the schema arrises in my view only for the validation. 
I have not checked other objects, but one way around this could be to put these objects into the `definitions` where currently date_from, date_to, etc. are defined and then make a reference at the above mentioned leaf of the schema. 
I see this not as a priority, but still wanted to bring this up. If others also encounter this then maybe it's a nice-to-have for the future.

**Comment by abohara** [comment]
@heikowestermann @stephenholleran Unless there is anything new, I suggest we close it.

**Comment by heikowestermann** [comment]
@abohara @stephenholleran agreed
