### ISSUE TITLE
[schema] calibration object should contain calibration_id instead of report_file_name

### ISSUE THREAD

**Issue by heikowestermann** [IEA-Task-43/digital_wra_data_standard#72]
Since the `calibration` object already contains a `report_link` property, should the `report_file_name` property be replaced with a report/calibration id? From a lab standpoint the calibration id is the unique id for a calibration so it's a good indexer here. Alternatively the calibration id could be also be added as an additional property.

**Comment by kersting** [comment]
@heikowestermann What is the definition of report_link? is it a web link? Also, I think that the report ID is not so important for the analyst unless I am missing something on how this could influence the results of an analysis.

**Comment by stephenholleran** [comment]
We decided to add `calibration_id` to the WRA Data Model as this is an id to identify a specific calibration from the calibration organization. `calibration_id` is also in the digital calibration certificate and so it is a simple mapping.

Do not make it required.
