### ISSUE TITLE
Should we create a new field for time offset?

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#73]
@stephenholleran offset_from_utc_hrs covers when a device is offset to a certain time zone; however, it does not cover when the time in the logger is entered incorrectly. This affects primarily legacy data given that most of the loggers and remote sensing devices are time synchronized. Still there is a lot of legacy data and time offsets show up in installation documents and need to be accounted by the analyst. I propose an additional field called time_offset_from_installation or logger_time_offset to account for such problems.

**Comment by stephenholleran** [comment]
@kersting @abohara 
A solution could be to expand the description of the existing `offset_from_utc_hrs` to include an incorrect time programmed into the logger. 
Agreed during meeting on 8th April 2021
