### ISSUE TITLE
measurement_type_id additional types

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#74]
@stephenholleran specially remote sensing devices have very specific measurement types that probably should be added to the current list. The following types should be at least brought to a discussion.

1. Info flags and status flags (probably we can fit all under flags or have it as statistic_type_id under quality).
2. Packets (packets with rain, packets with fog and the comments above probably fit this as well).
3. Tilt (we already have tilt_x, tilt_y, tilt_z but tilt is also reported as the scalar product of tilt_x and tilt_y).
4. Wipe counts
5. Voltage (Should we make a distinction between voltage from battery and voltage from external power sources; for example, generator or fuel cell system?)

**Comment by stephenholleran** [comment]
@kersting @abohara 
From our discussion on 8th April 2021 we were discussing the possibility of creating a naming convention of something like `temperature_status`. @abohara please give a better example?

What we do is tag on the `statistic_type` onto the measurement_point name e.g. `Logger_Tmp_avg`, `Logger_tmp_count`.


- [ ] Add `flag` to measurement_type enums.

- [ ] Add `tilt` to measurement_type enums to go along with tilt_x, tilt_y, tilt_z?

**Comment by kersting** [comment]
@stephenholleran I like the naming convention idea. Anemoi had some sort of naming convention. We have a naming convention that we'd be happy to share but even what we have would require some polishing.

**Comment by stephenholleran** [comment]
**Meeting on 22-Apr-2021**
Give guidance on how to create a new measurement_type, that is "the target" +  "_" + "type" e.g. "air_temperature" or "logger_voltage". ("Target" might not be the correct word?)

This guidance is to help contributors to create new measurement_types.

I'm still confused about this so I won't do anything on it yet.

**Comment by kersting** [comment]
@stephenholleran I suggest using the words device and sensor instead of target given that you're referencing that to a measurement and it will always be either a device such as a lidar or a sensor such as a temperature sensor.
