### ISSUE TITLE
[DCC] Request for template existing calibration certificates

### ISSUE THREAD

**Issue by stephenholleran** [IEA-Task-43/digital_wra_data_standard#75]
Request sample calibration certificates from wind tunnel calibration facilities in order to have a baseline for making sure the digital calibration certificate is satisfied.

**Comment by kersting** [comment]
@heikowestermann Please shoot me an email with wind tunnels under measnet and I'll contact them.

**Comment by abohara** [comment]
@sdsmdp Would any of the facilities you use be able to share sample calibration certs ?
