### ISSUE TITLE
[DCC] meeting notes

### ISSUE THREAD

**Issue by stephenholleran** [IEA-Task-43/digital_wra_data_standard#77]
**Meeting 15-Apr-2021**
Attendees: SH, GK, JF, HW, MP, VC, AB

issue #75 
GK got SOH calibration template. Upload to Google Docs?
HW will send on his.
MP will reach out next week.

**Jumped back into reviewing the draft DCC with HW:**

- `calibration_id` - a unique identifier assigned to the calibration. Not globally unique on it's own but is when combined with an accreditation_id.
Called 'Certificate number' in SOH, 'Calibration Mark' for DW, 'Calibration Mark' for Ammonit 
Sonic anemometers has 3 calibration ids and for Thies 1st Class X has 2 (store 1st calibration as establishments and then 2nd checks, wind analyst will use the 2nd one but the 1st ones are written into the sensor).
**Conclusion**: Use `calibration_id` but expand the description to outline what this number refers to in each certificate.

- `calibration_lab` make the `contact` less formal and include `company_name` and `address`.
**Action:** everyone to check what sort of contact details are included in the template certs they have.

**Comment by kersting** [comment]
@stephenholleran Could you please update the meeting request including the link for Google Drive so people can have access to the calibration certificate templates?

**Comment by stephenholleran** [comment]
**Meeting 29-Apr-2021**
AB, GK, SH, MH, HW

- `calibration_lab` continuation.. address is just the business address as it may be different from the `place_of_calibration`. Just use a single string for the address. Make if not required.
- `customer` keep it simple with just `name` and `address`. Keep `reference` as it could be used for and order number, PO number, etc.
- `test_item` information about the sensor
   - `serial_number` a single or multiple serial numbers? Include customer number? How to handle body + cup serial numbers? Decided to ignore the customer serial number. Decided to combine a body + cup serial number into a single serial number. In the description outline the procedure for combining them: body,cup,other

Action: HW to check how Vector provide their serial numbers.

**Comment by stephenholleran** [comment]
**Meeting 27-May-2021**
AB, GK, SH, HW

- HW found out that the Vector packaging has two separate serial numbers for body and cup on the packaging. They are not joining them together in any specific way. This doesn't change our conclusions from the previous meeting.
- `description` is to say what the sensor is. We could use the `sensor_type` that already exists in the data model. It was agreed to do that.
- `manufacturer` contains company name and address. Rename to `oem`.
- `setup` - `date_of_calibration` is good.
- `procedure` is the name of the procedure used. Leave it as free field.
- `wind_tunnel` Identification of the wind tunnel the calibration took place. Can be used as part of the `place_of_calibration` if we need it? We don't need `place_of_calibration` and we will rename `wind_tunnel` to `wind_tunnel_id`.
- `mounting_diameter` vertical boom mount for anemometers, similar to `upstand_diameter` in the data model. Using a `quantity` type which includes uncertainty. This uncertainty isn't needed here so don't make it required. Make an enum for the `units`.

**Comment by stephenholleran** [comment]
**Meeting 10-Jun-2021**
SH, HW, GK, MH, MP

- Carrying on from 'setup' and 'units' for the quantity of 'mounting diameter'. Use a single enum for 'units'. Copy from the WRA Data Model. Just use metric.
- 'setup' - 'mounting_orientation': add a good description, this is good as it is, it is referenced clockwise from 0 degrees with 0 pointing towards the wind.
- 'setup' - 'ambient_conditions': list off the 3 standard; temperature, pressure and humidity. Make them optional. Allow Avg, Max, Min. Allow users to add in others as optional.
- MP to talk to folks within his organisation that know more about calibrations and see if they would be interested in joining.

**Comment by stephenholleran** [comment]
**Meeting 24-Jun-2021**
SH, HW, AB

- We went through some open issues and made comments where we thought we could.
   - closed request for calibration templates.
   - Decided to add `calibration_id` to calibration in the WRA Data Model.
   - Update `place_of_calibration` description to state that it maps to `wind_tunnel_id` in the DCC.
   - With regards issue #86 we decided to move ambient conditions into `results` as these are measured during the actual calibration.
- We went through calibration results focusing on the table of results. No decisions were made but the table structure was discussed. It was also noted that we probably need to improve the WRA Data Model `calibration_uncertainty` - `uncertainty` description to link to the DCC deviation uncertainty. **Find out exactly what is required for the WRA DM.**


**Send reminder to everyone for the next meeting as we will be making decisions about the uncertainty table.**

**Comment by stephenholleran** [comment]
**Meeting 22-Jul-2021**

- Deviation (difference between reference and test item) uncertainty is the one that is used in the IEC power curve test. **Action** @stephenholleran: update to description in the WRA Data Model. Call it `combined_uncertainty`. 
- Reviewed the data table and how the uncertainties are recorded. **Action**  @heikowestermann Send email and Slack msg to outline the direction we are going with the uncertainty table. Ask for them to give feedback and we can have a discussion at the next meeting.
- Went through the `Result` > `Linear Regression` section. This contains the `slope` and `offset` that wind analyst are interested in. All looks good and nobody had any issues with it.
- `date_of_issue` a simple date format. Nothing of note.
- `revision` revision information in case the calibration needs to be updated. **Action** @stephenholleran The `date_of_issue` may not change so therefore we need to include `revision` in the WRA Data Model.

**Comment by stephenholleran** [comment]
**16-Sep-2021**
HW, SH, GK, MP, TA

Seems like I lost my notes from 2 weeks ago. The actions from that meeting were to invite all the calibration facilities to agree a version 1 during this meeting.

No other calibration facilities turned up so we agreed to release the version 1. As the digita_calibration_certificate is part of the WRA Data Model we decided to promote the whole repo to a version 1 and keep (for now) the DCC as part of the overall WRA.

**Comment by kersting** [comment]
@stephenholleran and @heikowestermann I think that this release is worth it a big release in different platforms (slack, LinkedIn, etc).

**Comment by stephenholleran** [comment]
**30-Sep-2021**
HW, SH, GK, MP

1. Review SOH comments. 
   - Most of their comments in the email were accepted.
   - `Mounting arrangement` as a string? Using a string might be problematic to future IEC recommendations on using multiple ultra-sonic sensors to derive a single wind speed. We think it should be a numeric however @heikowestermann **will create an issue and ask SOH to explain a bit more.**
2. Reviewed what other changes need to be made to DCC and WRA Data Model to close off the DCC project.
3. Reviewed some pull requests.
4. Schedule for release
   - Close off DCC on the 14th.
   - Add additional issues to the WRA and then sign off on v1.0 on the 28th.

**Comment by stephenholleran** [comment]
**14-Oct-2021**
SH, GK, AB

DCC
1. It was decided that the conversation in #113 satisfies the issues raised by SOH. **Actions: @heikowestermann to update based on that and also from the other already agreed issues raised by SOH.**

WRA Data Model issues

2. 'Mast_geometery_id' @agrangaraj could you provide an example for a hybrid structure in the issue #104?
3. 'Number of levels' we don't think this is appropriate to include. See comments in issue #104.
4. 'logger-main_config' **Action SH** include in issue #105 an explanation for how to add additional properties to a JSON without breaking the core schema.
5. Issues raised in #106: @agrangaraj could you explain more about what 'Sound (db)' would entail? 
   We are not inclined to include turbine specific parameters as it is out of scope. A general 'power' is already accounted for.
   Parameters u, v, w are interesting to include. **Action SH** We will include the generic u, v, w that is not related to wind speed to capture cases we can't think of at the moment. For 'w' include in the description that we already have 'vertical_wind_speed' and users should be using this parameter for vertical wind speed and not the w.

**Comment by stephenholleran** [comment]
**11-Nov-2021**
SH, HW, MP

Updates:

1. Task 43 Fall meeting was on last week and this. Lots of discussions about what each package is doing, how to work together and what the overall task is to deliver. The org committee are pulling the feedback together to produce tasks for the last year of the project. December 10th for reporting back. May reach out before then with surveys.
2. Still no sign of the CFARS config file. **Check if this is the file https://github.com/CFARS/site_suitability_tool/blob/main/Configuration_template.xlsx Response from CFARS: _That is the first part of the participant’s config that is needed. The next piece is the additional information the vestas group needs. They have sent me slides for that info and I just have to pick out the information from that deck, find what’s different, and add that to the list. Have to do the same with the 15-1 info I acquired as well._**

DCC:

1. HW any update on pull request to dev? **Need to work on Read Me. Issue with software that was used to create images. Can release as is but lets see if issues can be resolved.**

WRA Data Model:

1. SH has done nothing. Task 43 fall meeting used up all my time.
2. Task 37 produced a YAML data model for a wind plant and turbine. https://github.com/IEAWindTask37/windIO Do we want to link into that project, especially on the 'plant' side of things? **Interesting to reach out but how useful will it be for us at this moment in time? Would be useful for organizations that implement the data model as a database internally as the measurement location can be part of a plant. _Action SH: create issue to remember to look at it after version 1._**
3. Pick up where we left off on the sensor classification issue. **We think MP's post above is a good suggestion and can capture future changes easier. Another use case could be, if the lab publishes the anemometer measurements then it may be possible for a user to take these, set their own S terrain and use the software to calculate the classification value for that S terrain. _Action for next meeting could be to write requirements in an issue._**
4. Issue #119 explicit coordinate system. **We think this is a good idea. Go back to the requester asking how they might suggest implementing it or rephrasing the description.**

AOB:

1. SH is out the next 2 Thursdays (18th and 25th (_also Thanksgiving_)). Do you still want to have these calls? **Cancel the 25th, keep the 18th**

**Comment by stephenholleran** [comment]
# 9-Dec-2021

SH, HW

**DCC:**

1. Pull request? **Went through a bit of the pull request. More to do. We will try and do this remotely so we don't need the call on the 23rd.**

**WRA Data Model:**

1. Pull request for 'logger_main_config' #105, allow additional properties.
2. Pull request for meas_types #106, u, v, w and cumulative_energy.
3. New field for WKID (Well Known ID) to better define the coordinate system or put in description? #119 Is this something that is set or defined by the user? **We should define what the coordinate system should be to avoid confusion. Having an attribute called WKID suggests to the user that they can set the coordinate system they are using. This can cause major confusion and updates to the Data Model as we would then have to account for Easting and Northing. It was decided to just update the description to be more specific about the coordinate system everyone should use.**
4. #88 uncertainty classification of anemometers. **An enum is good but where do we store it; in the schema or some other json/db/csv? Because it is data it makes sense to have it outside the schema. There are only about 5 or 6 anemometers though. By having it separate from the schema would allow anemometer manufacturers to add in a new anemometer classification or update (with reviews). Avoids needing to release a new version of the schema each time it is updated. The schema would need an enum list of anemometer models (uuid/ids) which would then match the stored classification information. We would still need a place to put in the classification values into the implemented data model. Therefore we would need to add a 'classification' property to store the value e.g. 0.9A. 3.2B or 2.7S. Could use regex to validate. We went with the name 'classification' as it is not wrong however 'class index' or 'class number' might just refer to the number part. HW to look into what info regarding the classification and how to structure it. SH will add classification to the schema.**

**AOB**

1. **Investigate using GitHub Discussion as it might be a useful place for hosting blogs or something. Bring it up in the other call.**
1. This is the last technical call of the year? Next one would be the 23rd, SH is not available.

**Comment by stephenholleran** [comment]
@heikowestermann @kersting @sdsmdp @abohara @Dynorat @SFO-SOH @ponce10 
The digital calibration certificate branch is now merged into the dev branch. See pull request #125.

Thanks very much for everyone's contribution and especially @heikowestermann for driving this forward!

I will close these DCC meeting notes. Our usual Thursday technical call will move onto the next topic where we will have a new set of meeting notes. Thanks again!
