### ISSUE TITLE
[SQL] measurement_point_sensor move date_from and date_to from sensor into this table

### ISSUE THREAD

**Issue by stephenholleran** [IEA-Task-43/digital_wra_data_standard#79]
Scenario:
How does a user know when a `measurement_point` ends? At present it comes from the `date_to` in the sensor table however a sensor should be able to be associated with another measurement_point without having to replicate it. Therefore I am proposing moving the `date_from` and date_to` fields up from the sensor table into the measurement_point_sensor mapping table.

This has no impact on the JSON Schema, just the relational diagram / SQL database.

**Comment by kersting** [comment]
@stephenholleran Can we discuss this in the next meeting? I'm not sure I follow it. I don't understand what you mean by having to replicate it.

**Comment by stephenholleran** [comment]
**Meeting 22-Apr-2021**
Agreed that this is a reasonable thing to do.

Brings up the question of measurement_point again. I will create a new issues for that.
