### ISSUE TITLE
Find a place for additional documentation

### ISSUE THREAD

**Issue by flrs-edf** [IEA-Task-43/digital_wra_data_standard#81]
I think it would be great if we can find a central place for presentations we gave about the standard, meeting notes, etc. I suggest that we use this repo's Wiki page for this. We can link to presentations, videos, etc. from there.

Opinions?

**Comment by stephenholleran** [comment]
I've never used the GitHub Wiki before so not sure what it is like. But from a bit of reading it sounds good.

Are you able to put your PowerPoint and other files like that into the Wiki?

**Comment by kersting** [comment]
@flrs-edf That looks like a cool option. Any chance that you could give a 15 minute presentation on the best way to organize GitHub Wiki and your experiences with it?

**Comment by abohara** [comment]
We should be able to upload presentations atleast.  That would avoid relying on a 3rd part storage service. @flrs-edf  or @stephenholleran , would you like to upload your slides if you are comfortable sharing?

**Comment by flrs-edf** [comment]
@abohara I have no problem with sharing them!

@stephenholleran As far a I know you cannot upload files. We would have to share links to files uploaded somewhere else.

@kersting I am sorry I am unqualified to present on the topic. I do not use GitHub wikis all that often. I was just trying to find the easiest way for us to share information.

**Comment by stephenholleran** [comment]
We can just share the Google Drive link and just make it view only or something like that. That works for me as my presentation is already on the IEA Task 43 Google Drive.

**Comment by abohara** [comment]
@stephenholleran @flrs-edf @kersting 

I have created a very basic Home page and a presentations page as the starting point for the wiki. What has worked for me as a 'starting' point previously, is a home page that has a list / link of all sub pages (for. e.g. Presentations ) and keeping things relatively shallow (2 levels). 

I was convinced there was a way to upload files into the wiki here but it appears you can't do so in a wiki (though you can upload things into comments like these). 

So, @flrs-edf I agree with using the wiki as a way to document things and @stephenholleran agree with keeping the presentation in other drives and linking to it from the wiki. Please feel free to edit pages as you see fit ( or change it drastically beyond my starting template)
