### ISSUE TITLE
Adding firmware version in logger_main_config

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#87]
Loggers, lidar, and sodars may have a firmware update that can change data and metadata. I propose it adding to the logger_main_config given that this can change over time.

**Comment by stephenholleran** [comment]
@kersting
I think this is a fair enough attribute to add to logger_main_config. For lidars the WindCube firmware or software version can have an impact on the format of the resulting data file. I think for loggers it doesn't have much if any impact but we should probably include it for the lidars sake.

@abohara what do you think?

What would we call it?
`firmware_version`
`software_version` (called by Ammonit in a Meteo40 logger)
`hardware_rev` (this is what it is called in NRG SymphoniePro logger)
`version` (Leosphere in a WindCube which I don't think is good)
ZX have CSV Converter, Filter, Averager, File system version

**Comment by abohara** [comment]
@kersting @stephenholleran 
Definitely agree we should have a version tracking.

`firmware_version` - seems to make the sense, since software often designed to go immediately above the hardware layer is called software. `software` I think is usually programs a little closer to the user and higher level of abstraction.

We should confirm if `hardware_rev` from NRG, actually just means the `firmware_version` or truly tracks hardware level changes (may be a circuit board swap ? ). I suspect its the former in which case `firmware_version` would suffice. Perhaps @sdsmdp  can confirm

For ZX, maybe we can combine all the different versions into one string and put under the `firmware_version`.

Thoughts ?

**Comment by stephenholleran** [comment]
I would lean towards `firmware_version` too.

**abohara:**
> For ZX, maybe we can combine all the different versions into one string and put under the firmware_version.

This field will be a free field so yes, I would image the user will be able to concat a few versions together.

**Comment by kersting** [comment]
@stephenholleran and @abohara I think `firmware_version` is good but we need to make sure we add in the description cases such as the ZX one.

**Comment by sdsmdp** [comment]
I agree with @kersting  that, in the absence of discrete attributes to breakdown compound or structured version numbers, some kind of free form description field must be available and, I propose, be a required field so recipients know how to parse the `firmware_version` provided.

@abohara, `hardware_rev` as used by NRG means a board spin (e.g., "Rev. G" board). This is separate and distinct from the `firmware_version`, (e.g., 3.2.3) that represents the revision of the logger firmware. See the attached screenshot from SymphoniePRO Desktop for an example.

![LoggerConfigBlock](https://user-images.githubusercontent.com/50709588/124655802-58a66200-de6e-11eb-91d8-8d3bfac2e4e7.png)

Note that revving firmware is not necessarily required upon a board spin (if the hardware revision is intended to be backward compatible, for example, which is often the case).

That said, whether you need to capture `hardware_rev` at all may still be a valid question. Unless a hardware rev (of any device) could result in a change in device behavior or data output or interpretation, I posit that such change as a result of a hardware revision is not likely and is thus not important to analysts. However, analysts are not the only potential recipients of data values. This value can be useful for providing technical support. Customers often share one or more data files when seeking technical support. This attribute helps our staff know exactly what hardware a customer is using. I imagine other manufacturers have a similar need. I know that hardware revisions are applicable for lidars, too. Therefore, even though analysts may ignore the attribute, I do think supporting this attribute in data files remains a good idea. That's my two cents.

**Comment by kersting** [comment]
@stephenholleran I agree your statement about `hardware_version`

**Comment by BiancaMorandi** [comment]
@kersting I see that `logger_firmware_version` is an 'Optional' field but 'cannot be null'. Shouldn't be allowed for this field to be Null as it is optional? All other Optional fields in `logger_main_config` can be null.

![image](https://user-images.githubusercontent.com/65398058/193050400-7147ab64-e800-4b34-985b-06ee39c7ab02.png)

cc @stephenholleran

**Comment by stephenholleran** [comment]
Yeah, it looks like it is inconsistent with the rest of the variables in logger_main_config so I am ok for it to be added.
