### ISSUE TITLE
Uncertainty for acquisition system

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#89]
In IEC-61400-12-1 and 2 it is necessary to report also uncertainty from acquisition system. I propose a discussion on the use of uncertainty parameters for the acquisition system under the logger_model table.

**Comment by abohara** [comment]
Sounds good @kersting . I support the discussion. Generally, I assume these are very small uncertainties and up to the discretion of the res. assmt team. However, if there are some numbers provided by the OEM or in some way obtained through the measurement campaign then it makes sense to have it here.

**Comment by kersting** [comment]
@abohara They're small indeed (in the order of 0.2% to 0.4% if I'm not mistaken) but they're present in any power performance test report provided by any consultant.

**Comment by stephenholleran** [comment]
@kersting are you able to provide an example or screen shot so we can better understand? Thanks.

**Comment by kersting** [comment]
@stephenholleran Here is an example for the NRG T60. You can see the accuracy row on the bottom (same as uncertainty). To convert that to uncertainty in energy there is some math that it is necessary but the bottom line is that this is the input for that IEC calculation.

![image](https://user-images.githubusercontent.com/19154103/124653362-d3698000-de62-11eb-894a-2a4d4e8a86f8.png)

**Comment by stephenholleran** [comment]
@kersting I think you meant that for issue #88 
I'll paste it over.

This issue is for the acquisition system.
